import { Package, TelegramChannel } from "../types";

export const PACKAGES: Package[] = [
  // 24 Hours
  { id: "1-D1", name: "Package 1-D1 (1000 Channels)", channels: 1000, priceBDT: 400, durationDays: 1 },
  { id: "2-D1", name: "Package 2-D1 (1500 Channels)", channels: 1500, priceBDT: 700, durationDays: 1 },
  { id: "3-D1", name: "Package 3-D1 (2500 Channels)", channels: 2500, priceBDT: 900, durationDays: 1 },
  { id: "4-D1", name: "Package 4-D1 (5000 Channels)", channels: 5000, priceBDT: 1900, durationDays: 1 },
  // 1 Week
  { id: "1-W1", name: "Package 1-W1 (1000 Channels)", channels: 1000, priceBDT: 1000, durationDays: 7 },
  { id: "2-W1", name: "Package 2-W1 (1500 Channels)", channels: 1500, priceBDT: 1500, durationDays: 7 },
  { id: "3-W1", name: "Package 3-W1 (2500 Channels)", channels: 2500, priceBDT: 2500, durationDays: 7 },
  { id: "4-W1", name: "Package 4-W1 (5000 Channels)", channels: 5000, priceBDT: 4000, durationDays: 7 },
  // Lifetime
  { id: "Lifetime", name: "Package Lifetime (5000 Channels)", channels: 5000, priceBDT: 122000, priceUSD: 1000, durationDays: 36500 },
];

export const getChannels1000 = () => {
  const data = {
    "1": { name: "MYLF", link: "https://t.me/mylfed" },
    "2": { name: "Koi no Yokan", link: "https://t.me/Koianime" },
    "3": { name: "ANIME WORLD 1", link: "https://t.me/ANIME_W1" },
    "4": { name: "@vickyy_san", link: "https://t.me/hdwallpaper4k4u" },
    "5": { name: "✅ Заявки принимаются", link: "https://t.me/animewallpaperfons" },
    "6": { name: "manga", link: "https://t.me/animemangaxtutti" },
    "7": { name: "Universe", link: "https://t.me/AnimeWallpaperUniverse" },
    "8": { name: "Son dibujos", link: "https://t.me/dibujosdedospersonasaburridas" },
    "9": { name: "Russua Aonha", link: "https://t.me/+cz6WONf9vM44NTgy" },
    "10": { name: "NSFW Warning", link: "https://t.me/+Zm4DUbJarvVmMGJk" },
    "11": { name: "Onku", link: "https://t.me/+L_yNHFEMBqVmZGYx" },
    "12": { name: "Hentai Universe", link: "https://t.me/+ueyQhA5sPplkZGE0" },
    "13": { name: "3D Jav", link: "https://t.me/+gBudv_7KJ_5kYjJl" },
    "14": { name: "Hentai Hunters", link: "https://t.me/+INFQKge4AJU1YmU9" },
    "15": { name: "Naruto", link: "https://t.me/+Au8dsm6UW9tjMzI1" },
    "16": { name: "Lewd Cosplay", link: "https://t.me/+S2-_xgIVljA0MzE1" },
    "17": { name: "Pantsu", link: "https://t.me/+6BFQ5JT_poIzMjVl" },
    "18": { name: "SWF", link: "https://t.me/GaleriaDelCosplay" },
    "19": { name: "Pokeputas", link: "https://t.me/+JibMn7AYUT04Njk5" },
    "20": { name: "Rule 34", link: "https://t.me/+sk_EOo9YkmIxNDMy" },
    "21": { name: "Hentai Anal", link: "https://t.me/+QLBK8Vz7kjNmOWZl" },
    "22": { name: "Quintessential", link: "https://t.me/+itYTq5Rjky1mYTg1" },
    "23": { name: "Fairy tale", link: "https://t.me/+iEcSuVOm-1w1M2I1" },
    "24": { name: "Genshin Impact", link: "https://t.me/+BZhmU7N2ohwxOTk1" },
    "25": { name: "Latex cosplay", link: "https://t.me/+7Mb7FA8hB11hN2M1" },
    "26": { name: "Furry Hentai", link: "https://t.me/+prQM6T_7W-k1MjA1" },
    "27": { name: "ecchi", link: "https://t.me/+lSwmbqmVz582NjE1" },
    "28": { name: "more:3", link: "https://t.me/+bkNUnqpPFqgyZWYx" },
    "29": { name: "e-nada", link: "https://t.me/+49LIjQvIDKpmMjBh" },
    "30": { name: "Paizuri", link: "https://t.me/+gFBTrUMDcbU1OGE9" },
    "31": { name: "pokemon", link: "https://t.me/+-Fz1ZDv8ELE1NTQ1" },
    "32": { name: "kill la kill", link: "https://t.me/+fdGll5f1ovMwNWJl" },
    "33": { name: "hunter x hunter", link: "https://t.me/+W0vuvAPbGJhmODll" },
    "34": { name: "Lewd Neko", link: "https://t.me/+LZPD3cpJh9wzMTNl" },
    "35": { name: "Bunny Girls", link: "https://t.me/+7qHu2SOKeodhMjM1" },
    "36": { name: "thick", link: "https://t.me/+W71kiYLSTvM2NDQ1" },
    "37": { name: "Bondage", link: "https://t.me/+llOR1o-_iRk3Mzc1" },
    "38": { name: "Jam", link: "https://t.me/+l0g6CtbOxNM2YzUy" },
    "39": { name: "Ooko Opai", link: "https://t.me/+BNsNJBn1bTw4ZDAx" },
    "40": { name: "MoChinas", link: "https://t.me/+gKC2q_m_GNo1ZmNh" },
    "41": { name: "wota TBO", link: "https://t.me/+Y8SWxi43L10zM2Ey" },
    "42": { name: "Fap Zone", link: "https://t.me/+D4ecHyacQZY2MmE1" },
    "43": { name: "Booty", link: "https://t.me/+px5gTDpOyLgyMWQ0" },
    "44": { name: "DP152's", link: "https://t.me/+1rTP1fJhMANmM2Ex" },
    "45": { name: "horny house", link: "https://t.me/+a3XAb5ez6SVlNmIy" },
    "46": { name: "CumZone", link: "https://t.me/+ppXmSjwb4GRhZTgx" },
    "47": { name: "Hentai Randome", link: "https://t.me/+Ugm8mcVyvr1iZmIx" },
    "48": { name: "Dujin Dump", link: "https://t.me/+THRWQwTbfF1iNTM1" },
    "49": { name: "Kokoro Network", link: "https://t.me/KokoroNetwork" },
    "50": { name: "Asian Beauty", link: "https://t.me/+7rw8W3QZvlc3MmMy" },
    "51": { name: "Utopian Leaks", link: "https://telegram.me/utopianleaks" },
    "52": { name: "Pr00n", link: "https://telegram.me/pornodrive" },
    "53": { name: "Featured Creators 🔞", link: "https://telegram.me/joinchat/AW5EqAiG8UFlOGFh" },
    "54": { name: "Public Nu,dity", link: "https://telegram.me/random_porn" },
    "55": { name: "pfff_boom", link: "https://telegram.me/pfff_boom" },
    "56": { name: "Luciddreams", link: "https://t.me/luciddreams?start=_tgr_Yf_iCF1mOWU1" },
    "57": { name: "leecherxxx", link: "https://telegram.me/leecherxxx" },
    "58": { name: "Home Clips", link: "https://telegram.me/eronude" },
    "59": { name: "Bad Girls Videos", link: "https://t.me/+PpozazutRQg3YmU1" },
    "60": { name: "XXX Cloud", link: "https://telegram.me/joinchat/5EXKTI8kXA9iZjYy" },
    "61": { name: "Classic 18+", link: "https://telegram.me/classic_adult_films" },
    "62": { name: "Braz,zers", link: "https://telegram.me/joinchat/AAAAAFjVzKcL6FstTIhCnA" },
    "63": { name: "Cum on Face", link: "https://telegram.me/cumoffface" },
    "64": { name: "Dirt,y Memes", link: "https://telegram.me/DirtyMemesHub" },
    "65": { name: "telepo,rnogram", link: "https://telegram.me/telepornogram" },
    "66": { name: "Na,ked_tiktok2", link: "https://telegram.me/Naked_tiktok2" },
    "67": { name: "Exo,tic Videos", link: "https://telegram.me/joinchat/RmEKYbsZaexiYjIy" },
    "68": { name: "CINEMA", link: "https://telegram.me/joinchat/LE5THapOc0k4MTAy" },
    "69": { name: "Telegram Porn,stars", link: "https://telegram.me/BinanceBoxDaily" },
    "70": { name: "tattoos", link: "https://telegram.me/tattoos" },
    "71": { name: "Ga,y World", link: "https://telegram.me/gaypornworld" },
    "72": { name: "Tender Feet", link: "https://telegram.me/nyfeet" },
    "73": { name: "Real S,ex", link: "https://telegram.me/sexwife" },
    "74": { name: "explicit_scenes", link: "https://telegram.me/explicit_scenes" },
    "75": { name: "Explicit photos", link: "https://telegram.me/joinchat/AAAAAEQRBwcHqlrq977gkg" },
    "76": { name: "Double Penetration", link: "https://telegram.me/joinchat/COmq5d2L148zNjY0" },
    "77": { name: "Beautiful Girls", link: "https://telegram.me/b_babes" },
    "78": { name: "Naughty_America_premiumz", link: "https://telegram.me/Naughty_America_premiumz" },
    "79": { name: "Love BIte", link: "https://telegram.me/joinchat/AAAAAEphQ8XA8mzLTZxfBQ" },
    "80": { name: "Real Amature", link: "https://telegram.me/RealAmateursNG" },
    "81": { name: "Celebrity", link: "https://telegram.me/feets_soles" },
    "82": { name: "Full Length Vodeo", link: "https://telegram.me/joinchat/PjSZki6ofj04N2M5" },
    "83": { name: "Erot,icon", link: "https://telegram.me/clitorus" },
    "84": { name: "AI Girls", link: "https://telegram.me/ai_girls_beauty" },
    "85": { name: "Club 18", link: "https://telegram.me/BBCFWC" },
    "86": { name: "Hot Milf", link: "https://telegram.me/assmilfhots" },
    "87": { name: "Savage Black", link: "https://telegram.me/joinchat/AAAAAEKM_lvu5Yj9jdoUqw" },
    "88": { name: "Se..Xy Bu.tt", link: "https://telegram.me/buttsexy" },
    "89": { name: "Public Se,x", link: "https://telegram.me/joinchat/zxbDc-qaEZEwYWE6" },
    "90": { name: "Indian Girls", link: "https://telegram.me/desihotpobn" },
    "91": { name: "English Comics", link: "https://telegram.me/hellaway" },
    "92": { name: "Bad Girls", link: "https://t.me/+PpozazutRQg3YmU1" },
    "93": { name: "Ero,tic 18+", link: "https://telegram.me/myerotic" },
    "94": { name: "Les,bian", link: "https://telegram.me/joinchat/dZC_mNET07U4YzMy" },
    "95": { name: "sex,o_pedia", link: "https://telegram.me/sexo_pedia" },
    "96": { name: "laugaixinh", link: "https://telegram.me/laugaixinh" },
    "97": { name: "JapanesePorno", link: "https://telegram.me/JapanesePorno" },
    "98": { name: "BestAsianGirls", link: "https://telegram.me/BestAsianGirls" },
    "99": { name: "Cheati,ngWifes", link: "https://telegram.me/CheatingWifes" },
    "100": { name: "Porn 18+,", link: "https://telegram.me/joinchat/AAAAAEbyHdEum3w26SBQVQ" },
    "101": { name: "Asian Deshi", link: "https://telegram.me/sexyasian" },
    "102": { name: "Indian Bhabi", link: "https://telegram.me/joinchat/AAAAAE6Gs9ebxKJdvpUivg" },
    "103": { name: "indianadultcomics", link: "https://telegram.me/indianadultcomics" },
    "104": { name: "18+ Asian S,ex", link: "https://telegram.me/AsianSex" },
    "105": { name: "Dating chat 18++", link: "https://t.me/joinchat/qHYoXqFwPN4zOWFi" },
    "106": { name: "Mom son", link: "https://t.me/joinchat/7A8T9ooh8YU1ODQ1" },
    "107": { name: "देशी 🔞", link: "https://t.me/joinchat/JRoao0ARxgMzZTdl" },
    "108": { name: "English movie", link: "https://t.me/joinchat/Z_jFDbw-LklhY2Q1" },
    "109": { name: "4k pron video teraboxx", link: "https://t.me/joinchat/iJJnwnHZED0wMjNl" },
    "110": { name: "𝘼𝙡𝙡 𝙩𝙮𝙥𝙚𝙨 𝙫𝙞𝙙𝙚𝙤", link: "https://t.me/joinchat/IgOc0k48pusxNmFl" },
    "111": { name: "𝗗𝗮𝘁𝗶𝗻𝗴", link: "https://t.me/Chatting_Swapping_Dating" },
    "112": { name: "Instagram Group Girls", link: "https://t.me/joinchat/hepW0dFOSzcwZTll" },
    "113": { name: "𝗠𝗔𝗦𝗔𝗟𝗔🌶𝗖𝗛𝗔𝗧𝗭💋", link: "https://t.me/Masala_ChatzZ" },
    "114": { name: "World chatting", link: "https://t.me/joinchat/A9x59Pb2vIFhY2U1" },
    "115": { name: "Desi aunty lovers", link: "https://t.me/desiauntylover09" },
    "116": { name: "Pron 4k Movie 4K", link: "https://t.me/joinchat/9nuljHCBpVE4NmJl" },
    "117": { name: "ᴄʜᴀᴛᴛɪɴɢ ɢʀᴏᴜᴘ", link: "https://t.me/worldchatiinggroup" },
    "118": { name: "𝗪𝗢𝗥𝗟𝗗 𝗖𝗛𝗔𝗧𝗧𝗜𝗡𝗚 𝗚𝗥𝗢𝗨𝗣 👩‍❤️‍👨", link: "https://t.me/joinchat/b98sqTX5k1NjNjFh" },
    "119": { name: "CUTE GIRLS CHATTING", link: "https://t.me/cute_girls_chatting_group" },
    "120": { name: "👙Desi Porn Collections", link: "https://t.me/Desi_Porn_Collections" },
    "121": { name: "Tamil Housewife", link: "https://t.me/joinchat/8Q-pNFZsezM1ZjBl" },
    "122": { name: "Ｔａｍｉｌ Ｃｏｕｐｌｅｓ 💞", link: "https://t.me/tamilcouplesswap_chat" },
    "123": { name: "Girl's chatting", link: "https://t.me/joinchat/8fw0ZsB5LzYwNGU1" },
    "124": { name: "ᑭOᗰ🍒ᑭOᗰ 💬", link: "https://t.me/joinchat/KPWGoLOxyx9kNTll" },
    "125": { name: "Beautiful world 😍", link: "https://t.me/joinchat/gXJDUi-2P65kYzEx" },
    "126": { name: "Romantic friend", link: "https://t.me/joinchat/CuTJsS1HpvJhMGNl" },
    "127": { name: "Тошкен 71", link: "https://t.me/Towkent_chat_No1" },
    "128": { name: "Delhi Noida", link: "https://t.me/joinchat/0q_OWxWYK5xmOGFl" },
    "129": { name: "Kolkata Sexy Girl", link: "https://t.me/joinchat/B0ithb2HbyMxNDBl" },
    "130": { name: "Haryana Punjab Group", link: "https://t.me/GayWorldGIG" },
    "131": { name: "𝐒𝐎𝐑𝐆𝐀𝐋𝐎𝐆𝐀𝐌⚘ ⸙", link: "https://t.me/tamil_tamilhotchat" },
    "132": { name: "Hot ❤️ Hot ❤️", link: "https://t.me/joinchat/wT5J0D35fykzNWJl" },
    "133": { name: "Tamil verified couples💎", link: "https://t.me/Tamilcouples_verifiedcouples" },
    "134": { name: "MOM SON GROUP", link: "https://t.me/joinchat/HAG0DR2KDhdmOGVl" },
    "135": { name: "𝐂𝐎𝐔𝐏𝐋𝐄 𝐒𝐖𝐀𝐏 🐝", link: "https://t.me/joinchat/jvLYN9KPezJmMTQ1" },
    "136": { name: "Naughty Girls", link: "https://t.me/joinchat/RMychC3-V1w4YWM1" },
    "137": { name: "Viral Video Terabox", link: "https://t.me/joinchat/-sl_FkW-0GpkNWM1" },
    "138": { name: "Bangalore Dating", link: "https://t.me/bangalore_realmeet" },
    "139": { name: "Chat and mate", link: "https://t.me/joinchat/RqLk6e1ip_djN2Nl" },
    "140": { name: "Wife swapping", link: "https://t.me/joinchat/4Xahi2-Ri8U3MWU1" },
    "141": { name: "Confession X", link: "https://t.me/joinchat/OB0DCbOT7nU5ODg1" },
    "142": { name: "Kerala dating/hookup", link: "https://t.me/joinchat/ntWCj3StvRkwNDVl" },
    "143": { name: "𝕄𝕒𝕝𝕝𝕦 𝔾𝕒𝕪 ℍ𝕦𝕓", link: "https://t.me/mallugay_club" },
    "144": { name: "Desi Village girls", link: "https://t.me/joinchat/0siPFAlpU6EyY2Nl" },
    "145": { name: "Tamil Voice Chat 💋", link: "https://t.me/joinchat/5jVVyY3gpDJhMzll" },
    "146": { name: "𝗙𝗥𝗜𝗘𝗡𝗗𝗦 𝗖𝗛𝗔𝗧𝗧𝗜𝗡𝗚 𝗭𝗢𝗡𝗘 🦋🌷", link: "https://t.me/Freinds_group_hindi_grp" },
    "147": { name: "மங்கையர் விடுதி", link: "https://t.me/joinchat/ERIOefFy6HhiOWFl" },
    "148": { name: "International dating", link: "https://t.me/joinchat/WX12xstwSqE2YmE1" },
    "149": { name: "𝖪𝖾𝗋𝖺𝗅𝖺 𝖢𝖮𝖴𝖯𝖫𝖤𝖲 SWAP 𝖹𝗈𝗇𝖾 💋", link: "https://t.me/keralacoupleswap_chat" },
    "150": { name: "Kannada chatting group", link: "https://t.me/kannada_chatting_group4" },
    "151": { name: "🝮︎︎︎︎︎︎︎ 𝐍𝐀𝐔𝐆𝐇𝐓𝐘 𝐂𝐇𝐀𝐓𝐓𝐈𝐍𝐆 ✿︎", link: "https://t.me/joinchat/u1CuEzo5tWczZDk1" },
    "152": { name: "HOT GIRLS 🫣", link: "https://t.me/girls_group_world" },
    "153": { name: "Tollywood Beautys 💃 🔥💦", link: "https://t.me/joinchat/F-piXg1iRy8xNGJl" },
    "154": { name: "𝙍𝙄𝙎𝙆 𝙍𝙀𝙋𝙊𝙎𝙏", link: "https://t.me/joinchat/lpLd1Yd5PxBlNWM1" },
    "155": { name: "Video 🔞", link: "https://t.me/sexyvideo344" },
    "156": { name: "Sleeping pills 💊💦", link: "https://t.me/joinchat/4Imz9ih-AfA4MjM1" },
    "157": { name: "Cuckold World 2.0", link: "https://t.me/joinchat/ZQ5rrjj1jk4wYWEx" },
    "158": { name: "𝐂𝐚𝐦 𝐒𝐡𝐨𝐰 𝐙𝐨𝐧𝐞", link: "https://t.me/camshowzone" },
    "159": { name: "Tamil Couples freedom Hub 💞", link: "https://t.me/tamilfantasy_couples" },
    "160": { name: "Sleeping pills backup 💊💦", link: "https://t.me/joinchat/Kjf3yvF2Chw0MGQ1" },
    "161": { name: "🇭𝗼𝗧 🇳𝗶𝗴𝗵𝘁 🇨𝗹𝘂𝗯 🇲𝗮𝘀𝘁𝗶", link: "https://t.me/joinchat/GjkqWxN9Vwo0N2U0" },
    "162": { name: "Cum tribute 🍑", link: "https://t.me/joinchat/wXMwIXQYltMyODVl" },
    "163": { name: "Pʀᴏɴ hub 🔞", link: "https://t.me/joinchat/r75CtoOBRdcyOTY9" },
    "164": { name: "𝙍𝙀𝘿 𝙕𝙊𝙉𝙀", link: "https://t.me/joinchat/-8-utPPQx5I5ZjI1" },
    "165": { name: "Shikari backup", link: "https://t.me/joinchat/C35FFFyBEjthMDg1" },
    "166": { name: "Paid video call Indian", link: "https://t.me/cam_call_video_paid" },
    "167": { name: "Punjabi nazare 🥵", link: "https://t.me/joinchat/VboYmi3-BzE3NTE1" },
    "168": { name: "Bangalore Friends", link: "https://t.me/bangaloreFriends_club" },
    "169": { name: "COUPLE TO COUPLE", link: "https://t.me/joinchat/6qRoiAzxqNAwYTNl" },
    "170": { name: "Friendship X", link: "https://t.me/joinchat/WoqdIr6A_ZQzYzll" },
    "171": { name: "Kuwait ChatMatesUnite 🇰🇼", link: "https://t.me/ChatMatesUnite" },
    "172": { name: "Reena Babhi 💋💋", link: "https://t.me/joinchat/H4SqJZ8l3r9iNzc9" },
    "173": { name: "Desi hot 🥵 video", link: "https://t.me/joinchat/xHC38ij5eyEyNjE9" },
    "174": { name: "அடிச்சா 🫂கத்தாத டி💋", link: "https://t.me/joinchat/4vaesrG6WMs0ZWE9" },
    "175": { name: "hidden carmra", link: "https://t.me/joinchat/s9dZ80E0blZiNDk1" },
    "176": { name: "Desi girls", link: "https://t.me/desisexygirl67" },
    "177": { name: "Couple chatting", link: "https://t.me/wife_soping" },
    "178": { name: "Gujarati Wife", link: "https://t.me/Gujarat_wife_swapping" },
    "179": { name: "Mom son backup demo", link: "https://t.me/joinchat/6j6DXgMEZcNjZDk1" },
    "180": { name: "◄❥͜͡⃟⃝💖🩹꯭᪳𝄄─̌இரகசிய தோழி─", link: "https://t.me/joinchat/lyuvfyW6fLUwNTll" },
    "181": { name: "Desi hot 🧒 girl", link: "https://t.me/doxx699" },
    "182": { name: "Risk Repost🔥", link: "https://t.me/riskrepostreshare" },
    "183": { name: "🍒🇹‌𝐞𝐥𝐮𝐠𝐮 🇭‌𝐨𝐭 🇬‌𝐢𝐫𝐥𝐬 🇦‌𝐧𝐝 🇧‌𝐨𝐲𝐬🍒", link: "https://t.me/joinchat/sBR61EBy8wY3OGY1" },
    "184": { name: "Hot web series", link: "https://t.me/joinchat/TOk9WU6G3m41NmZl" },
    "185": { name: "🇽𝑌 ᯾ 𝐅𝐑𝐈𝐄𝐍𝐃𝐒𝐇𝐈𝐏 𝐙𝐎𝐍𝐄", link: "https://t.me/joinchat/bBS6OBwl-DphYjdk" },
    "186": { name: "Just Chatz 18+❤️", link: "https://t.me/chatinghuball" },
    "187": { name: "🇹𝅛𝆭𝐌𝐄𝐏𝐀𝐒𝐒 🇩𝐄𝐏𝐀𝐑𝐓𝐌𝐄𝐍𝐓』", link: "https://t.me/TIMEPASS_DEPARTMENT" },
    "188": { name: "Desi Fun", link: "https://t.me/desifundesi" },
    "189": { name: "𝙄𝙉𝘿𝙄𝘼𝙉 WIFE 𝙎𝙒𝘼𝙋𝙋𝙄𝙉𝙂", link: "https://t.me/real_swapping_wife_couple" },
    "190": { name: "Sleeping pills 3.0", link: "https://t.me/joinchat/BrwmNN-fd09hNDZl" },
    "191": { name: "ˡ᭄𝒈𝒊𝒓𝒍s Chatting ǤroนƤ☬꧂", link: "https://t.me/joinchat/csiJ8VNvrOA0ZTZl" },
    "192": { name: "𝗖𝗢𝗙𝗙𝗘𝗘 𝗖𝗛𝗔𝗧 ☕【﻿𝗖𝗖】", link: "https://t.me/randomcoffeequest" },
    "193": { name: "ⓖⓞⓞⓓ ⓒⓐⓜ", link: "https://t.me/joinchat/xhqukdM-iQhhMmE9" },
    "194": { name: "🕶️ 𝓥𝓪𝓪𝓷𝓰𝓴𝓪 𝓟𝓪𝔃𝓱𝓪𝓰𝓪𝓵𝓪𝓪𝓶 💥", link: "https://t.me/joinchat/WSpRVOylqR44NzY1" },
    "195": { name: "BLR PARTIES & NIGHTLIFE", link: "https://t.me/Bangalore_Parties_And_Fun" },
    "196": { name: "Telegram 4k Pron link", link: "https://t.me/joinchat/HAMPrHs8hKIyYTE1" },
    "197": { name: "꧁Teℓนgน꧂🔥HOT🔥", link: "https://t.me/joinchat/a4lY5gjoUdc2OGZl" },
    "198": { name: "Missed video club ( Chat )", link: "https://t.me/m_v_club_chat" },
    "199": { name: "Delhi cuck", link: "https://t.me/delhincrcucck" },
    "200": { name: "ACTRESS HUB - chat group", link: "https://t.me/actressHUBing" },
    "201": { name: "WIFE SWAPPING ✨", link: "https://t.me/bullsforcuxks" },
    "202": { name: "Sec sex", link: "https://t.me/joinchat/Cm1PP8vLc-k3Mjk9" },
    "203": { name: "Punjab Haryana wife swapping", link: "https://t.me/punjabharyanawifeswaping" },
    "204": { name: "Bangladeshi 18+", link: "https://t.me/Bangladeshi_18_x" },
    "205": { name: "Only Bangla Adult Videos", link: "https://t.me/onlybanglaadultvideos" },
    "206": { name: "Bangladeshi Adult Xxx", link: "https://t.me/engkishkha" },
    "207": { name: "BENGALI MOM LOVER 💋", link: "https://t.me/+9-1fM6mg-8oxYjFl" },
    "208": { name: "কল বয় সার্ভিস 2.0", link: "https://t.me/arav378" },
    "209": { name: "ꜱᴇx ɢʀᴏᴜᴘ ʙᴅ", link: "https://t.me/+ihF_uvvY7i05ZDU1" },
    "210": { name: "naya Bangladeshi xxx videos 👙", link: "https://t.me/naya_bangladeshi" },
    "211": { name: "BangladeshiMouni roy xxx videos", link: "https://t.me/mx_player_website_netpal_bot" },
    "212": { name: "Bangladeshi girl rape videos", link: "Bangladeshi girl rape videos" },
    "213": { name: "Bangladeshi sexvideo🥵", link: "https://t.me/xxxvideo_pronvideo_adultvideo_x" },
    "214": { name: "XXX VIDEOS BANGLADESH 💦🥒🩱", link: "https://t.me/wwwxxxxncom" },
    // Add more here manually 
  };
  return Object.values(data);
};

export const getChannels1500 = () => {
  const data = {
    "1": { name: "MYLF", link: "https://t.me/mylfed" },
    "2": { name: "Koi no Yokan", link: "https://t.me/Koianime" },
    "3": { name: "ANIME WORLD 1", link: "https://t.me/ANIME_W1" },
    "4": { name: "@vickyy_san", link: "https://t.me/hdwallpaper4k4u" },
    "5": { name: "✅ Заявки принимаются", link: "https://t.me/animewallpaperfons" },
    "6": { name: "manga", link: "https://t.me/animemangaxtutti" },
    "7": { name: "Universe", link: "https://t.me/AnimeWallpaperUniverse" },
    "8": { name: "Son dibujos", link: "https://t.me/dibujosdedospersonasaburridas" },
    "9": { name: "Russua Aonha", link: "https://t.me/+cz6WONf9vM44NTgy" },
    "10": { name: "NSFW Warning", link: "https://t.me/+Zm4DUbJarvVmMGJk" },
    "11": { name: "Onku", link: "https://t.me/+L_yNHFEMBqVmZGYx" },
    "12": { name: "Hentai Universe", link: "https://t.me/+ueyQhA5sPplkZGE0" },
    "13": { name: "3D Jav", link: "https://t.me/+gBudv_7KJ_5kYjJl" },
    "14": { name: "Hentai Hunters", link: "https://t.me/+INFQKge4AJU1YmU9" },
    "15": { name: "Naruto", link: "https://t.me/+Au8dsm6UW9tjMzI1" },
    "16": { name: "Lewd Cosplay", link: "https://t.me/+S2-_xgIVljA0MzE1" },
    "17": { name: "Pantsu", link: "https://t.me/+6BFQ5JT_poIzMjVl" },
    "18": { name: "SWF", link: "https://t.me/GaleriaDelCosplay" },
    "19": { name: "Pokeputas", link: "https://t.me/+JibMn7AYUT04Njk5" },
    "20": { name: "Rule 34", link: "https://t.me/+sk_EOo9YkmIxNDMy" },
    "21": { name: "Hentai Anal", link: "https://t.me/+QLBK8Vz7kjNmOWZl" },
    "22": { name: "Quintessential", link: "https://t.me/+itYTq5Rjky1mYTg1" },
    "23": { name: "Fairy tale", link: "https://t.me/+iEcSuVOm-1w1M2I1" },
    "24": { name: "Genshin Impact", link: "https://t.me/+BZhmU7N2ohwxOTk1" },
    "25": { name: "Latex cosplay", link: "https://t.me/+7Mb7FA8hB11hN2M1" },
    "26": { name: "Furry Hentai", link: "https://t.me/+prQM6T_7W-k1MjA1" },
    "27": { name: "ecchi", link: "https://t.me/+lSwmbqmVz582NjE1" },
    "28": { name: "more:3", link: "https://t.me/+bkNUnqpPFqgyZWYx" },
    "29": { name: "e-nada", link: "https://t.me/+49LIjQvIDKpmMjBh" },
    "30": { name: "Paizuri", link: "https://t.me/+gFBTrUMDcbU1OGE9" },
    "31": { name: "pokemon", link: "https://t.me/+-Fz1ZDv8ELE1NTQ1" },
    "32": { name: "kill la kill", link: "https://t.me/+fdGll5f1ovMwNWJl" },
    "33": { name: "hunter x hunter", link: "https://t.me/+W0vuvAPbGJhmODll" },
    "34": { name: "Lewd Neko", link: "https://t.me/+LZPD3cpJh9wzMTNl" },
    "35": { name: "Bunny Girls", link: "https://t.me/+7qHu2SOKeodhMjM1" },
    "36": { name: "thick", link: "https://t.me/+W71kiYLSTvM2NDQ1" },
    "37": { name: "Bondage", link: "https://t.me/+llOR1o-_iRk3Mzc1" },
    "38": { name: "Jam", link: "https://t.me/+l0g6CtbOxNM2YzUy" },
    "39": { name: "Ooko Opai", link: "https://t.me/+BNsNJBn1bTw4ZDAx" },
    "40": { name: "MoChinas", link: "https://t.me/+gKC2q_m_GNo1ZmNh" },
    "41": { name: "wota TBO", link: "https://t.me/+Y8SWxi43L10zM2Ey" },
    "42": { name: "Fap Zone", link: "https://t.me/+D4ecHyacQZY2MmE1" },
    "43": { name: "Booty", link: "https://t.me/+px5gTDpOyLgyMWQ0" },
    "44": { name: "DP152's", link: "https://t.me/+1rTP1fJhMANmM2Ex" },
    "45": { name: "horny house", link: "https://t.me/+a3XAb5ez6SVlNmIy" },
    "46": { name: "CumZone", link: "https://t.me/+ppXmSjwb4GRhZTgx" },
    "47": { name: "Hentai Randome", link: "https://t.me/+Ugm8mcVyvr1iZmIx" },
    "48": { name: "Dujin Dump", link: "https://t.me/+THRWQwTbfF1iNTM1" },
    "49": { name: "Kokoro Network", link: "https://t.me/KokoroNetwork" },
    "50": { name: "Asian Beauty", link: "https://t.me/+7rw8W3QZvlc3MmMy" },
    "51": { name: "Utopian Leaks", link: "https://telegram.me/utopianleaks" },
    "52": { name: "Pr00n", link: "https://telegram.me/pornodrive" },
    "53": { name: "Featured Creators 🔞", link: "https://telegram.me/joinchat/AW5EqAiG8UFlOGFh" },
    "54": { name: "Public Nu,dity", link: "https://telegram.me/random_porn" },
    "55": { name: "pfff_boom", link: "https://telegram.me/pfff_boom" },
    "56": { name: "Luciddreams", link: "https://t.me/luciddreams?start=_tgr_Yf_iCF1mOWU1" },
    "57": { name: "leecherxxx", link: "https://telegram.me/leecherxxx" },
    "58": { name: "Home Clips", link: "https://telegram.me/eronude" },
    "59": { name: "Bad Girls Videos", link: "https://t.me/+PpozazutRQg3YmU1" },
    "60": { name: "XXX Cloud", link: "https://telegram.me/joinchat/5EXKTI8kXA9iZjYy" },
    "61": { name: "Classic 18+", link: "https://telegram.me/classic_adult_films" },
    "62": { name: "Braz,zers", link: "https://telegram.me/joinchat/AAAAAFjVzKcL6FstTIhCnA" },
    "63": { name: "Cum on Face", link: "https://telegram.me/cumoffface" },
    "64": { name: "Dirt,y Memes", link: "https://telegram.me/DirtyMemesHub" },
    "65": { name: "telepo,rnogram", link: "https://telegram.me/telepornogram" },
    "66": { name: "Na,ked_tiktok2", link: "https://telegram.me/Naked_tiktok2" },
    "67": { name: "Exo,tic Videos", link: "https://telegram.me/joinchat/RmEKYbsZaexiYjIy" },
    "68": { name: "CINEMA", link: "https://telegram.me/joinchat/LE5THapOc0k4MTAy" },
    "69": { name: "Telegram Porn,stars", link: "https://telegram.me/BinanceBoxDaily" },
    "70": { name: "tattoos", link: "https://telegram.me/tattoos" },
    "71": { name: "Ga,y World", link: "https://telegram.me/gaypornworld" },
    "72": { name: "Tender Feet", link: "https://telegram.me/nyfeet" },
    "73": { name: "Real S,ex", link: "https://telegram.me/sexwife" },
    "74": { name: "explicit_scenes", link: "https://telegram.me/explicit_scenes" },
    "75": { name: "Explicit photos", link: "https://telegram.me/joinchat/AAAAAEQRBwcHqlrq977gkg" },
    "76": { name: "Double Penetration", link: "https://telegram.me/joinchat/COmq5d2L148zNjY0" },
    "77": { name: "Beautiful Girls", link: "https://telegram.me/b_babes" },
    "78": { name: "Naughty_America_premiumz", link: "https://telegram.me/Naughty_America_premiumz" },
    "79": { name: "Love BIte", link: "https://telegram.me/joinchat/AAAAAEphQ8XA8mzLTZxfBQ" },
    "80": { name: "Real Amature", link: "https://telegram.me/RealAmateursNG" },
    "81": { name: "Celebrity", link: "https://telegram.me/feets_soles" },
    "82": { name: "Full Length Vodeo", link: "https://telegram.me/joinchat/PjSZki6ofj04N2M5" },
    "83": { name: "Erot,icon", link: "https://telegram.me/clitorus" },
    "84": { name: "AI Girls", link: "https://telegram.me/ai_girls_beauty" },
    "85": { name: "Club 18", link: "https://telegram.me/BBCFWC" },
    "86": { name: "Hot Milf", link: "https://telegram.me/assmilfhots" },
    "87": { name: "Savage Black", link: "https://telegram.me/joinchat/AAAAAEKM_lvu5Yj9jdoUqw" },
    "88": { name: "Se..Xy Bu.tt", link: "https://telegram.me/buttsexy" },
    "89": { name: "Public Se,x", link: "https://telegram.me/joinchat/zxbDc-qaEZEwYWE6" },
    "90": { name: "Indian Girls", link: "https://telegram.me/desihotpobn" },
    "91": { name: "English Comics", link: "https://telegram.me/hellaway" },
    "92": { name: "Bad Girls", link: "https://t.me/+PpozazutRQg3YmU1" },
    "93": { name: "Ero,tic 18+", link: "https://telegram.me/myerotic" },
    "94": { name: "Les,bian", link: "https://telegram.me/joinchat/dZC_mNET07U4YzMy" },
    "95": { name: "sex,o_pedia", link: "https://telegram.me/sexo_pedia" },
    "96": { name: "laugaixinh", link: "https://telegram.me/laugaixinh" },
    "97": { name: "JapanesePorno", link: "https://telegram.me/JapanesePorno" },
    "98": { name: "BestAsianGirls", link: "https://telegram.me/BestAsianGirls" },
    "99": { name: "Cheati,ngWifes", link: "https://telegram.me/CheatingWifes" },
    "100": { name: "Porn 18+,", link: "https://telegram.me/joinchat/AAAAAEbyHdEum3w26SBQVQ" },
    "101": { name: "Asian Deshi", link: "https://telegram.me/sexyasian" },
    "102": { name: "Indian Bhabi", link: "https://telegram.me/joinchat/AAAAAE6Gs9ebxKJdvpUivg" },
    "103": { name: "indianadultcomics", link: "https://telegram.me/indianadultcomics" },
    "104": { name: "18+ Asian S,ex", link: "https://telegram.me/AsianSex" },
    "105": { name: "Dating chat 18++", link: "https://t.me/joinchat/qHYoXqFwPN4zOWFi" },
    "106": { name: "Mom son", link: "https://t.me/joinchat/7A8T9ooh8YU1ODQ1" },
    "107": { name: "देशी 🔞", link: "https://t.me/joinchat/JRoao0ARxgMzZTdl" },
    "108": { name: "English movie", link: "https://t.me/joinchat/Z_jFDbw-LklhY2Q1" },
    "109": { name: "4k pron video teraboxx", link: "https://t.me/joinchat/iJJnwnHZED0wMjNl" },
    "110": { name: "𝘼𝙡𝙡 𝙩𝙮𝙥𝙚𝙨 𝙫𝙞𝙙𝙚𝙤", link: "https://t.me/joinchat/IgOc0k48pusxNmFl" },
    "111": { name: "𝗗𝗮𝘁𝗶𝗻𝗴", link: "https://t.me/Chatting_Swapping_Dating" },
    "112": { name: "Instagram Group Girls", link: "https://t.me/joinchat/hepW0dFOSzcwZTll" },
    "113": { name: "𝗠𝗔𝗦𝗔𝗟𝗔🌶𝗖𝗛𝗔𝗧𝗭💋", link: "https://t.me/Masala_ChatzZ" },
    "114": { name: "World chatting", link: "https://t.me/joinchat/A9x59Pb2vIFhY2U1" },
    "115": { name: "Desi aunty lovers", link: "https://t.me/desiauntylover09" },
    "116": { name: "Pron 4k Movie 4K", link: "https://t.me/joinchat/9nuljHCBpVE4NmJl" },
    "117": { name: "ᴄʜᴀᴛᴛɪɴɢ ɢʀᴏᴜᴘ", link: "https://t.me/worldchatiinggroup" },
    "118": { name: "𝗪𝗢𝗥𝗟𝗗 𝗖𝗛𝗔𝗧𝗧𝗜𝗡𝗚 𝗚𝗥𝗢𝗨𝗣 👩‍❤️‍👨", link: "https://t.me/joinchat/b98sqTX5k1NjNjFh" },
    "119": { name: "CUTE GIRLS CHATTING", link: "https://t.me/cute_girls_chatting_group" },
    "120": { name: "👙Desi Porn Collections", link: "https://t.me/Desi_Porn_Collections" },
    "121": { name: "Tamil Housewife", link: "https://t.me/joinchat/8Q-pNFZsezM1ZjBl" },
    "122": { name: "Ｔａｍｉｌ Ｃｏｕｐｌｅｓ 💞", link: "https://t.me/tamilcouplesswap_chat" },
    "123": { name: "Girl's chatting", link: "https://t.me/joinchat/8fw0ZsB5LzYwNGU1" },
    "124": { name: "ᑭOᗰ🍒ᑭOᗰ 💬", link: "https://t.me/joinchat/KPWGoLOxyx9kNTll" },
    "125": { name: "Beautiful world 😍", link: "https://t.me/joinchat/gXJDUi-2P65kYzEx" },
    "126": { name: "Romantic friend", link: "https://t.me/joinchat/CuTJsS1HpvJhMGNl" },
    "127": { name: "Тошкен 71", link: "https://t.me/Towkent_chat_No1" },
    "128": { name: "Delhi Noida", link: "https://t.me/joinchat/0q_OWxWYK5xmOGFl" },
    "129": { name: "Kolkata Sexy Girl", link: "https://t.me/joinchat/B0ithb2HbyMxNDBl" },
    "130": { name: "Haryana Punjab Group", link: "https://t.me/GayWorldGIG" },
    "131": { name: "𝐒𝐎𝐑𝐆𝐀𝐋𝐎𝐆𝐀𝐌⚘ ⸙", link: "https://t.me/tamil_tamilhotchat" },
    "132": { name: "Hot ❤️ Hot ❤️", link: "https://t.me/joinchat/wT5J0D35fykzNWJl" },
    "133": { name: "Tamil verified couples💎", link: "https://t.me/Tamilcouples_verifiedcouples" },
    "134": { name: "MOM SON GROUP", link: "https://t.me/joinchat/HAG0DR2KDhdmOGVl" },
    "135": { name: "𝐂𝐎𝐔𝐏𝐋𝐄 𝐒𝐖𝐀𝐏 🐝", link: "https://t.me/joinchat/jvLYN9KPezJmMTQ1" },
    "136": { name: "Naughty Girls", link: "https://t.me/joinchat/RMychC3-V1w4YWM1" },
    "137": { name: "Viral Video Terabox", link: "https://t.me/joinchat/-sl_FkW-0GpkNWM1" },
    "138": { name: "Bangalore Dating", link: "https://t.me/bangalore_realmeet" },
    "139": { name: "Chat and mate", link: "https://t.me/joinchat/RqLk6e1ip_djN2Nl" },
    "140": { name: "Wife swapping", link: "https://t.me/joinchat/4Xahi2-Ri8U3MWU1" },
    "141": { name: "Confession X", link: "https://t.me/joinchat/OB0DCbOT7nU5ODg1" },
    "142": { name: "Kerala dating/hookup", link: "https://t.me/joinchat/ntWCj3StvRkwNDVl" },
    "143": { name: "𝕄𝕒𝕝𝕝𝕦 𝔾𝕒𝕪 ℍ𝕦𝕓", link: "https://t.me/mallugay_club" },
    "144": { name: "Desi Village girls", link: "https://t.me/joinchat/0siPFAlpU6EyY2Nl" },
    "145": { name: "Tamil Voice Chat 💋", link: "https://t.me/joinchat/5jVVyY3gpDJhMzll" },
    "146": { name: "𝗙𝗥𝗜𝗘𝗡𝗗𝗦 𝗖𝗛𝗔𝗧𝗧𝗜𝗡𝗚 𝗭𝗢𝗡𝗘 🦋🌷", link: "https://t.me/Freinds_group_hindi_grp" },
    "147": { name: "மங்கையர் விடுதி", link: "https://t.me/joinchat/ERIOefFy6HhiOWFl" },
    "148": { name: "International dating", link: "https://t.me/joinchat/WX12xstwSqE2YmE1" },
    "149": { name: "𝖪𝖾𝗋𝖺𝗅𝖺 𝖢𝖮𝖴𝖯𝖫𝖤𝖲 SWAP 𝖹𝗈𝗇𝖾 💋", link: "https://t.me/keralacoupleswap_chat" },
    "150": { name: "Kannada chatting group", link: "https://t.me/kannada_chatting_group4" },
    "151": { name: "🝮︎︎︎︎︎︎︎ 𝐍𝐀𝐔𝐆𝐇𝐓𝐘 𝐂𝐇𝐀𝐓𝐓𝐈𝐍𝐆 ✿︎", link: "https://t.me/joinchat/u1CuEzo5tWczZDk1" },
    "152": { name: "HOT GIRLS 🫣", link: "https://t.me/girls_group_world" },
    "153": { name: "Tollywood Beautys 💃 🔥💦", link: "https://t.me/joinchat/F-piXg1iRy8xNGJl" },
    "154": { name: "𝙍𝙄𝙎𝙆 𝙍𝙀𝙋𝙊𝙎𝙏", link: "https://t.me/joinchat/lpLd1Yd5PxBlNWM1" },
    "155": { name: "Video 🔞", link: "https://t.me/sexyvideo344" },
    "156": { name: "Sleeping pills 💊💦", link: "https://t.me/joinchat/4Imz9ih-AfA4MjM1" },
    "157": { name: "Cuckold World 2.0", link: "https://t.me/joinchat/ZQ5rrjj1jk4wYWEx" },
    "158": { name: "𝐂𝐚𝐦 𝐒𝐡𝐨𝐰 𝐙𝐨𝐧𝐞", link: "https://t.me/camshowzone" },
    "159": { name: "Tamil Couples freedom Hub 💞", link: "https://t.me/tamilfantasy_couples" },
    "160": { name: "Sleeping pills backup 💊💦", link: "https://t.me/joinchat/Kjf3yvF2Chw0MGQ1" },
    "161": { name: "🇭𝗼𝗧 🇳𝗶𝗴𝗵𝘁 🇨𝗹𝘂𝗯 🇲𝗮𝘀𝘁𝗶", link: "https://t.me/joinchat/GjkqWxN9Vwo0N2U0" },
    "162": { name: "Cum tribute 🍑", link: "https://t.me/joinchat/wXMwIXQYltMyODVl" },
    "163": { name: "Pʀᴏɴ hub 🔞", link: "https://t.me/joinchat/r75CtoOBRdcyOTY9" },
    "164": { name: "𝙍𝙀𝘿 𝙕𝙊𝙉𝙀", link: "https://t.me/joinchat/-8-utPPQx5I5ZjI1" },
    "165": { name: "Shikari backup", link: "https://t.me/joinchat/C35FFFyBEjthMDg1" },
    "166": { name: "Paid video call Indian", link: "https://t.me/cam_call_video_paid" },
    "167": { name: "Punjabi nazare 🥵", link: "https://t.me/joinchat/VboYmi3-BzE3NTE1" },
    "168": { name: "Bangalore Friends", link: "https://t.me/bangaloreFriends_club" },
    "169": { name: "COUPLE TO COUPLE", link: "https://t.me/joinchat/6qRoiAzxqNAwYTNl" },
    "170": { name: "Friendship X", link: "https://t.me/joinchat/WoqdIr6A_ZQzYzll" },
    "171": { name: "Kuwait ChatMatesUnite 🇰🇼", link: "https://t.me/ChatMatesUnite" },
    "172": { name: "Reena Babhi 💋💋", link: "https://t.me/joinchat/H4SqJZ8l3r9iNzc9" },
    "173": { name: "Desi hot 🥵 video", link: "https://t.me/joinchat/xHC38ij5eyEyNjE9" },
    "174": { name: "அடிச்சா 🫂கத்தாத டி💋", link: "https://t.me/joinchat/4vaesrG6WMs0ZWE9" },
    "175": { name: "hidden carmra", link: "https://t.me/joinchat/s9dZ80E0blZiNDk1" },
    "176": { name: "Desi girls", link: "https://t.me/desisexygirl67" },
    "177": { name: "Couple chatting", link: "https://t.me/wife_soping" },
    "178": { name: "Gujarati Wife", link: "https://t.me/Gujarat_wife_swapping" },
    "179": { name: "Mom son backup demo", link: "https://t.me/joinchat/6j6DXgMEZcNjZDk1" },
    "180": { name: "◄❥͜͡⃟⃝💖🩹꯭᪳𝄄─̌இரகசிய தோழி─", link: "https://t.me/joinchat/lyuvfyW6fLUwNTll" },
    "181": { name: "Desi hot 🧒 girl", link: "https://t.me/doxx699" },
    "182": { name: "Risk Repost🔥", link: "https://t.me/riskrepostreshare" },
    "183": { name: "🍒🇹‌𝐞𝐥𝐮𝐠𝐮 🇭‌𝐨𝐭 🇬‌𝐢𝐫𝐥𝐬 🇦‌𝐧𝐝 🇧‌𝐨𝐲𝐬🍒", link: "https://t.me/joinchat/sBR61EBy8wY3OGY1" },
    "184": { name: "Hot web series", link: "https://t.me/joinchat/TOk9WU6G3m41NmZl" },
    "185": { name: "🇽𝑌 ᯾ 𝐅𝐑𝐈𝐄𝐍𝐃𝐒𝐇𝐈𝐏 𝐙𝐎𝐍𝐄", link: "https://t.me/joinchat/bBS6OBwl-DphYjdk" },
    "186": { name: "Just Chatz 18+❤️", link: "https://t.me/chatinghuball" },
    "187": { name: "🇹𝅛𝆭𝐌𝐄𝐏𝐀𝐒𝐒 🇩𝐄𝐏𝐀𝐑𝐓𝐌𝐄𝐍𝐓』", link: "https://t.me/TIMEPASS_DEPARTMENT" },
    "188": { name: "Desi Fun", link: "https://t.me/desifundesi" },
    "189": { name: "𝙄𝙉𝘿𝙄𝘼𝙉 WIFE 𝙎𝙒𝘼𝙋𝙋𝙄𝙉𝙂", link: "https://t.me/real_swapping_wife_couple" },
    "190": { name: "Sleeping pills 3.0", link: "https://t.me/joinchat/BrwmNN-fd09hNDZl" },
    "191": { name: "ˡ᭄𝒈𝒊𝒓𝒍s Chatting ǤroนƤ☬꧂", link: "https://t.me/joinchat/csiJ8VNvrOA0ZTZl" },
    "192": { name: "𝗖𝗢𝗙𝗙𝗘𝗘 𝗖𝗛𝗔𝗧 ☕【﻿𝗖𝗖】", link: "https://t.me/randomcoffeequest" },
    "193": { name: "ⓖⓞⓞⓓ ⓒⓐⓜ", link: "https://t.me/joinchat/xhqukdM-iQhhMmE9" },
    "194": { name: "🕶️ 𝓥𝓪𝓪𝓷𝓰𝓴𝓪 𝓟𝓪𝔃𝓱𝓪𝓰𝓪𝓵𝓪𝓪𝓶 💥", link: "https://t.me/joinchat/WSpRVOylqR44NzY1" },
    "195": { name: "BLR PARTIES & NIGHTLIFE", link: "https://t.me/Bangalore_Parties_And_Fun" },
    "196": { name: "Telegram 4k Pron link", link: "https://t.me/joinchat/HAMPrHs8hKIyYTE1" },
    "197": { name: "꧁Teℓนgน꧂🔥HOT🔥", link: "https://t.me/joinchat/a4lY5gjoUdc2OGZl" },
    "198": { name: "Missed video club ( Chat )", link: "https://t.me/m_v_club_chat" },
    "199": { name: "Delhi cuck", link: "https://t.me/delhincrcucck" },
    "200": { name: "ACTRESS HUB - chat group", link: "https://t.me/actressHUBing" },
    "201": { name: "WIFE SWAPPING ✨", link: "https://t.me/bullsforcuxks" },
    "202": { name: "Sec sex", link: "https://t.me/joinchat/Cm1PP8vLc-k3Mjk9" },
    "203": { name: "Punjab Haryana wife swapping", link: "https://t.me/punjabharyanawifeswaping",
      "204": { name: "Bangladeshi 18+", link: "https://t.me/Bangladeshi_18_x" },
    "205": { name: "Only Bangla Adult Videos", link: "https://t.me/onlybanglaadultvideos" },
    "206": { name: "Bangladeshi Adult Xxx", link: "https://t.me/engkishkha" },
    "207": { name: "BENGALI MOM LOVER 💋", link: "https://t.me/+9-1fM6mg-8oxYjFl" },
    "208": { name: "কল বয় সার্ভিস 2.0", link: "https://t.me/arav378" },
    "209": { name: "ꜱᴇx ɢʀᴏᴜᴘ ʙᴅ", link: "https://t.me/+ihF_uvvY7i05ZDU1" },
    "210": { name: "naya Bangladeshi xxx videos 👙", link: "https://t.me/naya_bangladeshi" },
    "211": { name: "BangladeshiMouni roy xxx videos", link: "https://t.me/mx_player_website_netpal_bot" },
    "212": { name: "Bangladeshi girl rape videos", link: "Bangladeshi girl rape videos" },
    "213": { name: "Bangladeshi sexvideo🥵", link: "https://t.me/xxxvideo_pronvideo_adultvideo_x" },
    "214": { name: "XXX VIDEOS BANGLADESH 💦🥒🩱", link: "https://t.me/wwwxxxxncom" },
     },
    // Add more here manually
  };
  return Object.values(data);
};

export const getChannels2500 = () => {
  const data = {
    "1": { name: "MYLF", link: "https://t.me/mylfed" },
    "2": { name: "Koi no Yokan", link: "https://t.me/Koianime" },
    "3": { name: "ANIME WORLD 1", link: "https://t.me/ANIME_W1" },
    "4": { name: "@vickyy_san", link: "https://t.me/hdwallpaper4k4u" },
    "5": { name: "✅ Заявки принимаются", link: "https://t.me/animewallpaperfons" },
    "6": { name: "manga", link: "https://t.me/animemangaxtutti" },
    "7": { name: "Universe", link: "https://t.me/AnimeWallpaperUniverse" },
    "8": { name: "Son dibujos", link: "https://t.me/dibujosdedospersonasaburridas" },
    "9": { name: "Russua Aonha", link: "https://t.me/+cz6WONf9vM44NTgy" },
    "10": { name: "NSFW Warning", link: "https://t.me/+Zm4DUbJarvVmMGJk" },
    "11": { name: "Onku", link: "https://t.me/+L_yNHFEMBqVmZGYx" },
    "12": { name: "Hentai Universe", link: "https://t.me/+ueyQhA5sPplkZGE0" },
    "13": { name: "3D Jav", link: "https://t.me/+gBudv_7KJ_5kYjJl" },
    "14": { name: "Hentai Hunters", link: "https://t.me/+INFQKge4AJU1YmU9" },
    "15": { name: "Naruto", link: "https://t.me/+Au8dsm6UW9tjMzI1" },
    "16": { name: "Lewd Cosplay", link: "https://t.me/+S2-_xgIVljA0MzE1" },
    "17": { name: "Pantsu", link: "https://t.me/+6BFQ5JT_poIzMjVl" },
    "18": { name: "SWF", link: "https://t.me/GaleriaDelCosplay" },
    "19": { name: "Pokeputas", link: "https://t.me/+JibMn7AYUT04Njk5" },
    "20": { name: "Rule 34", link: "https://t.me/+sk_EOo9YkmIxNDMy" },
    "21": { name: "Hentai Anal", link: "https://t.me/+QLBK8Vz7kjNmOWZl" },
    "22": { name: "Quintessential", link: "https://t.me/+itYTq5Rjky1mYTg1" },
    "23": { name: "Fairy tale", link: "https://t.me/+iEcSuVOm-1w1M2I1" },
    "24": { name: "Genshin Impact", link: "https://t.me/+BZhmU7N2ohwxOTk1" },
    "25": { name: "Latex cosplay", link: "https://t.me/+7Mb7FA8hB11hN2M1" },
    "26": { name: "Furry Hentai", link: "https://t.me/+prQM6T_7W-k1MjA1" },
    "27": { name: "ecchi", link: "https://t.me/+lSwmbqmVz582NjE1" },
    "28": { name: "more:3", link: "https://t.me/+bkNUnqpPFqgyZWYx" },
    "29": { name: "e-nada", link: "https://t.me/+49LIjQvIDKpmMjBh" },
    "30": { name: "Paizuri", link: "https://t.me/+gFBTrUMDcbU1OGE9" },
    "31": { name: "pokemon", link: "https://t.me/+-Fz1ZDv8ELE1NTQ1" },
    "32": { name: "kill la kill", link: "https://t.me/+fdGll5f1ovMwNWJl" },
    "33": { name: "hunter x hunter", link: "https://t.me/+W0vuvAPbGJhmODll" },
    "34": { name: "Lewd Neko", link: "https://t.me/+LZPD3cpJh9wzMTNl" },
    "35": { name: "Bunny Girls", link: "https://t.me/+7qHu2SOKeodhMjM1" },
    "36": { name: "thick", link: "https://t.me/+W71kiYLSTvM2NDQ1" },
    "37": { name: "Bondage", link: "https://t.me/+llOR1o-_iRk3Mzc1" },
    "38": { name: "Jam", link: "https://t.me/+l0g6CtbOxNM2YzUy" },
    "39": { name: "Ooko Opai", link: "https://t.me/+BNsNJBn1bTw4ZDAx" },
    "40": { name: "MoChinas", link: "https://t.me/+gKC2q_m_GNo1ZmNh" },
    "41": { name: "wota TBO", link: "https://t.me/+Y8SWxi43L10zM2Ey" },
    "42": { name: "Fap Zone", link: "https://t.me/+D4ecHyacQZY2MmE1" },
    "43": { name: "Booty", link: "https://t.me/+px5gTDpOyLgyMWQ0" },
    "44": { name: "DP152's", link: "https://t.me/+1rTP1fJhMANmM2Ex" },
    "45": { name: "horny house", link: "https://t.me/+a3XAb5ez6SVlNmIy" },
    "46": { name: "CumZone", link: "https://t.me/+ppXmSjwb4GRhZTgx" },
    "47": { name: "Hentai Randome", link: "https://t.me/+Ugm8mcVyvr1iZmIx" },
    "48": { name: "Dujin Dump", link: "https://t.me/+THRWQwTbfF1iNTM1" },
    "49": { name: "Kokoro Network", link: "https://t.me/KokoroNetwork" },
    "50": { name: "Asian Beauty", link: "https://t.me/+7rw8W3QZvlc3MmMy" },
    "51": { name: "Utopian Leaks", link: "https://telegram.me/utopianleaks" },
    "52": { name: "Pr00n", link: "https://telegram.me/pornodrive" },
    "53": { name: "Featured Creators 🔞", link: "https://telegram.me/joinchat/AW5EqAiG8UFlOGFh" },
    "54": { name: "Public Nu,dity", link: "https://telegram.me/random_porn" },
    "55": { name: "pfff_boom", link: "https://telegram.me/pfff_boom" },
    "56": { name: "Luciddreams", link: "https://t.me/luciddreams?start=_tgr_Yf_iCF1mOWU1" },
    "57": { name: "leecherxxx", link: "https://telegram.me/leecherxxx" },
    "58": { name: "Home Clips", link: "https://telegram.me/eronude" },
    "59": { name: "Bad Girls Videos", link: "https://t.me/+PpozazutRQg3YmU1" },
    "60": { name: "XXX Cloud", link: "https://telegram.me/joinchat/5EXKTI8kXA9iZjYy" },
    "61": { name: "Classic 18+", link: "https://telegram.me/classic_adult_films" },
    "62": { name: "Braz,zers", link: "https://telegram.me/joinchat/AAAAAFjVzKcL6FstTIhCnA" },
    "63": { name: "Cum on Face", link: "https://telegram.me/cumoffface" },
    "64": { name: "Dirt,y Memes", link: "https://telegram.me/DirtyMemesHub" },
    "65": { name: "telepo,rnogram", link: "https://telegram.me/telepornogram" },
    "66": { name: "Na,ked_tiktok2", link: "https://telegram.me/Naked_tiktok2" },
    "67": { name: "Exo,tic Videos", link: "https://telegram.me/joinchat/RmEKYbsZaexiYjIy" },
    "68": { name: "CINEMA", link: "https://telegram.me/joinchat/LE5THapOc0k4MTAy" },
    "69": { name: "Telegram Porn,stars", link: "https://telegram.me/BinanceBoxDaily" },
    "70": { name: "tattoos", link: "https://telegram.me/tattoos" },
    "71": { name: "Ga,y World", link: "https://telegram.me/gaypornworld" },
    "72": { name: "Tender Feet", link: "https://telegram.me/nyfeet" },
    "73": { name: "Real S,ex", link: "https://telegram.me/sexwife" },
    "74": { name: "explicit_scenes", link: "https://telegram.me/explicit_scenes" },
    "75": { name: "Explicit photos", link: "https://telegram.me/joinchat/AAAAAEQRBwcHqlrq977gkg" },
    "76": { name: "Double Penetration", link: "https://telegram.me/joinchat/COmq5d2L148zNjY0" },
    "77": { name: "Beautiful Girls", link: "https://telegram.me/b_babes" },
    "78": { name: "Naughty_America_premiumz", link: "https://telegram.me/Naughty_America_premiumz" },
    "79": { name: "Love BIte", link: "https://telegram.me/joinchat/AAAAAEphQ8XA8mzLTZxfBQ" },
    "80": { name: "Real Amature", link: "https://telegram.me/RealAmateursNG" },
    "81": { name: "Celebrity", link: "https://telegram.me/feets_soles" },
    "82": { name: "Full Length Vodeo", link: "https://telegram.me/joinchat/PjSZki6ofj04N2M5" },
    "83": { name: "Erot,icon", link: "https://telegram.me/clitorus" },
    "84": { name: "AI Girls", link: "https://telegram.me/ai_girls_beauty" },
    "85": { name: "Club 18", link: "https://telegram.me/BBCFWC" },
    "86": { name: "Hot Milf", link: "https://telegram.me/assmilfhots" },
    "87": { name: "Savage Black", link: "https://telegram.me/joinchat/AAAAAEKM_lvu5Yj9jdoUqw" },
    "88": { name: "Se..Xy Bu.tt", link: "https://telegram.me/buttsexy" },
    "89": { name: "Public Se,x", link: "https://telegram.me/joinchat/zxbDc-qaEZEwYWE6" },
    "90": { name: "Indian Girls", link: "https://telegram.me/desihotpobn" },
    "91": { name: "English Comics", link: "https://telegram.me/hellaway" },
    "92": { name: "Bad Girls", link: "https://t.me/+PpozazutRQg3YmU1" },
    "93": { name: "Ero,tic 18+", link: "https://telegram.me/myerotic" },
    "94": { name: "Les,bian", link: "https://telegram.me/joinchat/dZC_mNET07U4YzMy" },
    "95": { name: "sex,o_pedia", link: "https://telegram.me/sexo_pedia" },
    "96": { name: "laugaixinh", link: "https://telegram.me/laugaixinh" },
    "97": { name: "JapanesePorno", link: "https://telegram.me/JapanesePorno" },
    "98": { name: "BestAsianGirls", link: "https://telegram.me/BestAsianGirls" },
    "99": { name: "Cheati,ngWifes", link: "https://telegram.me/CheatingWifes" },
    "100": { name: "Porn 18+,", link: "https://telegram.me/joinchat/AAAAAEbyHdEum3w26SBQVQ" },
    "101": { name: "Asian Deshi", link: "https://telegram.me/sexyasian" },
    "102": { name: "Indian Bhabi", link: "https://telegram.me/joinchat/AAAAAE6Gs9ebxKJdvpUivg" },
    "103": { name: "indianadultcomics", link: "https://telegram.me/indianadultcomics" },
    "104": { name: "18+ Asian S,ex", link: "https://telegram.me/AsianSex" },
    "105": { name: "Dating chat 18++", link: "https://t.me/joinchat/qHYoXqFwPN4zOWFi" },
    "106": { name: "Mom son", link: "https://t.me/joinchat/7A8T9ooh8YU1ODQ1" },
    "107": { name: "देशी 🔞", link: "https://t.me/joinchat/JRoao0ARxgMzZTdl" },
    "108": { name: "English movie", link: "https://t.me/joinchat/Z_jFDbw-LklhY2Q1" },
    "109": { name: "4k pron video teraboxx", link: "https://t.me/joinchat/iJJnwnHZED0wMjNl" },
    "110": { name: "𝘼𝙡𝙡 𝙩𝙮𝙥𝙚𝙨 𝙫𝙞𝙙𝙚𝙤", link: "https://t.me/joinchat/IgOc0k48pusxNmFl" },
    "111": { name: "𝗗𝗮𝘁𝗶𝗻𝗴", link: "https://t.me/Chatting_Swapping_Dating" },
    "112": { name: "Instagram Group Girls", link: "https://t.me/joinchat/hepW0dFOSzcwZTll" },
    "113": { name: "𝗠𝗔𝗦𝗔𝗟𝗔🌶𝗖𝗛𝗔𝗧𝗭💋", link: "https://t.me/Masala_ChatzZ" },
    "114": { name: "World chatting", link: "https://t.me/joinchat/A9x59Pb2vIFhY2U1" },
    "115": { name: "Desi aunty lovers", link: "https://t.me/desiauntylover09" },
    "116": { name: "Pron 4k Movie 4K", link: "https://t.me/joinchat/9nuljHCBpVE4NmJl" },
    "117": { name: "ᴄʜᴀᴛᴛɪɴɢ ɢʀᴏᴜᴘ", link: "https://t.me/worldchatiinggroup" },
    "118": { name: "𝗪𝗢𝗥𝗟𝗗 𝗖𝗛𝗔𝗧𝗧𝗜𝗡𝗚 𝗚𝗥𝗢𝗨𝗣 👩‍❤️‍👨", link: "https://t.me/joinchat/b98sqTX5k1NjNjFh" },
    "119": { name: "CUTE GIRLS CHATTING", link: "https://t.me/cute_girls_chatting_group" },
    "120": { name: "👙Desi Porn Collections", link: "https://t.me/Desi_Porn_Collections" },
    "121": { name: "Tamil Housewife", link: "https://t.me/joinchat/8Q-pNFZsezM1ZjBl" },
    "122": { name: "Ｔａｍｉｌ Ｃｏｕｐｌｅｓ 💞", link: "https://t.me/tamilcouplesswap_chat" },
    "123": { name: "Girl's chatting", link: "https://t.me/joinchat/8fw0ZsB5LzYwNGU1" },
    "124": { name: "ᑭOᗰ🍒ᑭOᗰ 💬", link: "https://t.me/joinchat/KPWGoLOxyx9kNTll" },
    "125": { name: "Beautiful world 😍", link: "https://t.me/joinchat/gXJDUi-2P65kYzEx" },
    "126": { name: "Romantic friend", link: "https://t.me/joinchat/CuTJsS1HpvJhMGNl" },
    "127": { name: "Тошкен 71", link: "https://t.me/Towkent_chat_No1" },
    "128": { name: "Delhi Noida", link: "https://t.me/joinchat/0q_OWxWYK5xmOGFl" },
    "129": { name: "Kolkata Sexy Girl", link: "https://t.me/joinchat/B0ithb2HbyMxNDBl" },
    "130": { name: "Haryana Punjab Group", link: "https://t.me/GayWorldGIG" },
    "131": { name: "𝐒𝐎𝐑𝐆𝐀𝐋𝐎𝐆𝐀𝐌⚘ ⸙", link: "https://t.me/tamil_tamilhotchat" },
    "132": { name: "Hot ❤️ Hot ❤️", link: "https://t.me/joinchat/wT5J0D35fykzNWJl" },
    "133": { name: "Tamil verified couples💎", link: "https://t.me/Tamilcouples_verifiedcouples" },
    "134": { name: "MOM SON GROUP", link: "https://t.me/joinchat/HAG0DR2KDhdmOGVl" },
    "135": { name: "𝐂𝐎𝐔𝐏𝐋𝐄 𝐒𝐖𝐀𝐏 🐝", link: "https://t.me/joinchat/jvLYN9KPezJmMTQ1" },
    "136": { name: "Naughty Girls", link: "https://t.me/joinchat/RMychC3-V1w4YWM1" },
    "137": { name: "Viral Video Terabox", link: "https://t.me/joinchat/-sl_FkW-0GpkNWM1" },
    "138": { name: "Bangalore Dating", link: "https://t.me/bangalore_realmeet" },
    "139": { name: "Chat and mate", link: "https://t.me/joinchat/RqLk6e1ip_djN2Nl" },
    "140": { name: "Wife swapping", link: "https://t.me/joinchat/4Xahi2-Ri8U3MWU1" },
    "141": { name: "Confession X", link: "https://t.me/joinchat/OB0DCbOT7nU5ODg1" },
    "142": { name: "Kerala dating/hookup", link: "https://t.me/joinchat/ntWCj3StvRkwNDVl" },
    "143": { name: "𝕄𝕒𝕝𝕝𝕦 𝔾𝕒𝕪 ℍ𝕦𝕓", link: "https://t.me/mallugay_club" },
    "144": { name: "Desi Village girls", link: "https://t.me/joinchat/0siPFAlpU6EyY2Nl" },
    "145": { name: "Tamil Voice Chat 💋", link: "https://t.me/joinchat/5jVVyY3gpDJhMzll" },
    "146": { name: "𝗙𝗥𝗜𝗘𝗡𝗗𝗦 𝗖𝗛𝗔𝗧𝗧𝗜𝗡𝗚 𝗭𝗢𝗡𝗘 🦋🌷", link: "https://t.me/Freinds_group_hindi_grp" },
    "147": { name: "மங்கையர் விடுதி", link: "https://t.me/joinchat/ERIOefFy6HhiOWFl" },
    "148": { name: "International dating", link: "https://t.me/joinchat/WX12xstwSqE2YmE1" },
    "149": { name: "𝖪𝖾𝗋𝖺𝗅𝖺 𝖢𝖮𝖴𝖯𝖫𝖤𝖲 SWAP 𝖹𝗈𝗇𝖾 💋", link: "https://t.me/keralacoupleswap_chat" },
    "150": { name: "Kannada chatting group", link: "https://t.me/kannada_chatting_group4" },
    "151": { name: "🝮︎︎︎︎︎︎︎ 𝐍𝐀𝐔𝐆𝐇𝐓𝐘 𝐂𝐇𝐀𝐓𝐓𝐈𝐍𝐆 ✿︎", link: "https://t.me/joinchat/u1CuEzo5tWczZDk1" },
    "152": { name: "HOT GIRLS 🫣", link: "https://t.me/girls_group_world" },
    "153": { name: "Tollywood Beautys 💃 🔥💦", link: "https://t.me/joinchat/F-piXg1iRy8xNGJl" },
    "154": { name: "𝙍𝙄𝙎𝙆 𝙍𝙀𝙋𝙊𝙎𝙏", link: "https://t.me/joinchat/lpLd1Yd5PxBlNWM1" },
    "155": { name: "Video 🔞", link: "https://t.me/sexyvideo344" },
    "156": { name: "Sleeping pills 💊💦", link: "https://t.me/joinchat/4Imz9ih-AfA4MjM1" },
    "157": { name: "Cuckold World 2.0", link: "https://t.me/joinchat/ZQ5rrjj1jk4wYWEx" },
    "158": { name: "𝐂𝐚𝐦 𝐒𝐡𝐨𝐰 𝐙𝐨𝐧𝐞", link: "https://t.me/camshowzone" },
    "159": { name: "Tamil Couples freedom Hub 💞", link: "https://t.me/tamilfantasy_couples" },
    "160": { name: "Sleeping pills backup 💊💦", link: "https://t.me/joinchat/Kjf3yvF2Chw0MGQ1" },
    "161": { name: "🇭𝗼𝗧 🇳𝗶𝗴𝗵𝘁 🇨𝗹𝘂𝗯 🇲𝗮𝘀𝘁𝗶", link: "https://t.me/joinchat/GjkqWxN9Vwo0N2U0" },
    "162": { name: "Cum tribute 🍑", link: "https://t.me/joinchat/wXMwIXQYltMyODVl" },
    "163": { name: "Pʀᴏɴ hub 🔞", link: "https://t.me/joinchat/r75CtoOBRdcyOTY9" },
    "164": { name: "𝙍𝙀𝘿 𝙕𝙊𝙉𝙀", link: "https://t.me/joinchat/-8-utPPQx5I5ZjI1" },
    "165": { name: "Shikari backup", link: "https://t.me/joinchat/C35FFFyBEjthMDg1" },
    "166": { name: "Paid video call Indian", link: "https://t.me/cam_call_video_paid" },
    "167": { name: "Punjabi nazare 🥵", link: "https://t.me/joinchat/VboYmi3-BzE3NTE1" },
    "168": { name: "Bangalore Friends", link: "https://t.me/bangaloreFriends_club" },
    "169": { name: "COUPLE TO COUPLE", link: "https://t.me/joinchat/6qRoiAzxqNAwYTNl" },
    "170": { name: "Friendship X", link: "https://t.me/joinchat/WoqdIr6A_ZQzYzll" },
    "171": { name: "Kuwait ChatMatesUnite 🇰🇼", link: "https://t.me/ChatMatesUnite" },
    "172": { name: "Reena Babhi 💋💋", link: "https://t.me/joinchat/H4SqJZ8l3r9iNzc9" },
    "173": { name: "Desi hot 🥵 video", link: "https://t.me/joinchat/xHC38ij5eyEyNjE9" },
    "174": { name: "அடிச்சா 🫂கத்தாத டி💋", link: "https://t.me/joinchat/4vaesrG6WMs0ZWE9" },
    "175": { name: "hidden carmra", link: "https://t.me/joinchat/s9dZ80E0blZiNDk1" },
    "176": { name: "Desi girls", link: "https://t.me/desisexygirl67" },
    "177": { name: "Couple chatting", link: "https://t.me/wife_soping" },
    "178": { name: "Gujarati Wife", link: "https://t.me/Gujarat_wife_swapping" },
    "179": { name: "Mom son backup demo", link: "https://t.me/joinchat/6j6DXgMEZcNjZDk1" },
    "180": { name: "◄❥͜͡⃟⃝💖🩹꯭᪳𝄄─̌இரகசிய தோழி─", link: "https://t.me/joinchat/lyuvfyW6fLUwNTll" },
    "181": { name: "Desi hot 🧒 girl", link: "https://t.me/doxx699" },
    "182": { name: "Risk Repost🔥", link: "https://t.me/riskrepostreshare" },
    "183": { name: "🍒🇹‌𝐞𝐥𝐮𝐠𝐮 🇭‌𝐨𝐭 🇬‌𝐢𝐫𝐥𝐬 🇦‌𝐧𝐝 🇧‌𝐨𝐲𝐬🍒", link: "https://t.me/joinchat/sBR61EBy8wY3OGY1" },
    "184": { name: "Hot web series", link: "https://t.me/joinchat/TOk9WU6G3m41NmZl" },
    "185": { name: "🇽𝑌 ᯾ 𝐅𝐑𝐈𝐄𝐍𝐃𝐒𝐇𝐈𝐏 𝐙𝐎𝐍𝐄", link: "https://t.me/joinchat/bBS6OBwl-DphYjdk" },
    "186": { name: "Just Chatz 18+❤️", link: "https://t.me/chatinghuball" },
    "187": { name: "🇹𝅛𝆭𝐌𝐄𝐏𝐀𝐒𝐒 🇩𝐄𝐏𝐀𝐑𝐓𝐌𝐄𝐍𝐓』", link: "https://t.me/TIMEPASS_DEPARTMENT" },
    "188": { name: "Desi Fun", link: "https://t.me/desifundesi" },
    "189": { name: "𝙄𝙉𝘿𝙄𝘼𝙉 WIFE 𝙎𝙒𝘼𝙋𝙋𝙄𝙉𝙂", link: "https://t.me/real_swapping_wife_couple" },
    "190": { name: "Sleeping pills 3.0", link: "https://t.me/joinchat/BrwmNN-fd09hNDZl" },
    "191": { name: "ˡ᭄𝒈𝒊𝒓𝒍s Chatting ǤroนƤ☬꧂", link: "https://t.me/joinchat/csiJ8VNvrOA0ZTZl" },
    "192": { name: "𝗖𝗢𝗙𝗙𝗘𝗘 𝗖𝗛𝗔𝗧 ☕【﻿𝗖𝗖】", link: "https://t.me/randomcoffeequest" },
    "193": { name: "ⓖⓞⓞⓓ ⓒⓐⓜ", link: "https://t.me/joinchat/xhqukdM-iQhhMmE9" },
    "194": { name: "🕶️ 𝓥𝓪𝓪𝓷𝓰𝓴𝓪 𝓟𝓪𝔃𝓱𝓪𝓰𝓪𝓵𝓪𝓪𝓶 💥", link: "https://t.me/joinchat/WSpRVOylqR44NzY1" },
    "195": { name: "BLR PARTIES & NIGHTLIFE", link: "https://t.me/Bangalore_Parties_And_Fun" },
    "196": { name: "Telegram 4k Pron link", link: "https://t.me/joinchat/HAMPrHs8hKIyYTE1" },
    "197": { name: "꧁Teℓนgน꧂🔥HOT🔥", link: "https://t.me/joinchat/a4lY5gjoUdc2OGZl" },
    "198": { name: "Missed video club ( Chat )", link: "https://t.me/m_v_club_chat" },
    "199": { name: "Delhi cuck", link: "https://t.me/delhincrcucck" },
    "200": { name: "ACTRESS HUB - chat group", link: "https://t.me/actressHUBing" },
    "201": { name: "WIFE SWAPPING ✨", link: "https://t.me/bullsforcuxks" },
    "202": { name: "Sec sex", link: "https://t.me/joinchat/Cm1PP8vLc-k3Mjk9" },
    "203": { name: "Punjab Haryana wife swapping", link: "https://t.me/punjabharyanawifeswaping",
    "204": { name: "Bangladeshi 18+", link: "https://t.me/Bangladeshi_18_x" },
    "205": { name: "Only Bangla Adult Videos", link: "https://t.me/onlybanglaadultvideos" },
    "206": { name: "Bangladeshi Adult Xxx", link: "https://t.me/engkishkha" },
    "207": { name: "BENGALI MOM LOVER 💋", link: "https://t.me/+9-1fM6mg-8oxYjFl" },
    "208": { name: "কল বয় সার্ভিস 2.0", link: "https://t.me/arav378" },
    "209": { name: "ꜱᴇx ɢʀᴏᴜᴘ ʙᴅ", link: "https://t.me/+ihF_uvvY7i05ZDU1" },
    "210": { name: "naya Bangladeshi xxx videos 👙", link: "https://t.me/naya_bangladeshi" },
    "211": { name: "BangladeshiMouni roy xxx videos", link: "https://t.me/mx_player_website_netpal_bot" },
    "212": { name: "Bangladeshi girl rape videos", link: "Bangladeshi girl rape videos" },
    "213": { name: "Bangladeshi sexvideo🥵", link: "https://t.me/xxxvideo_pronvideo_adultvideo_x" },
    "214": { name: "XXX VIDEOS BANGLADESH 💦🥒🩱", link: "https://t.me/wwwxxxxncom" },
    },
    // Add more here manually
  };
  return Object.values(data);
};

export const getChannels5000 = () => {
  const data = {
    "1": { name: "MYLF", link: "https://t.me/mylfed" },
    "2": { name: "Koi no Yokan", link: "https://t.me/Koianime" },
    "3": { name: "ANIME WORLD 1", link: "https://t.me/ANIME_W1" },
    "4": { name: "@vickyy_san", link: "https://t.me/hdwallpaper4k4u" },
    "5": { name: "✅ Заявки принимаются", link: "https://t.me/animewallpaperfons" },
    "6": { name: "manga", link: "https://t.me/animemangaxtutti" },
    "7": { name: "Universe", link: "https://t.me/AnimeWallpaperUniverse" },
    "8": { name: "Son dibujos", link: "https://t.me/dibujosdedospersonasaburridas" },
    "9": { name: "Russua Aonha", link: "https://t.me/+cz6WONf9vM44NTgy" },
    "10": { name: "NSFW Warning", link: "https://t.me/+Zm4DUbJarvVmMGJk" },
    "11": { name: "Onku", link: "https://t.me/+L_yNHFEMBqVmZGYx" },
    "12": { name: "Hentai Universe", link: "https://t.me/+ueyQhA5sPplkZGE0" },
    "13": { name: "3D Jav", link: "https://t.me/+gBudv_7KJ_5kYjJl" },
    "14": { name: "Hentai Hunters", link: "https://t.me/+INFQKge4AJU1YmU9" },
    "15": { name: "Naruto", link: "https://t.me/+Au8dsm6UW9tjMzI1" },
    "16": { name: "Lewd Cosplay", link: "https://t.me/+S2-_xgIVljA0MzE1" },
    "17": { name: "Pantsu", link: "https://t.me/+6BFQ5JT_poIzMjVl" },
    "18": { name: "SWF", link: "https://t.me/GaleriaDelCosplay" },
    "19": { name: "Pokeputas", link: "https://t.me/+JibMn7AYUT04Njk5" },
    "20": { name: "Rule 34", link: "https://t.me/+sk_EOo9YkmIxNDMy" },
    "21": { name: "Hentai Anal", link: "https://t.me/+QLBK8Vz7kjNmOWZl" },
    "22": { name: "Quintessential", link: "https://t.me/+itYTq5Rjky1mYTg1" },
    "23": { name: "Fairy tale", link: "https://t.me/+iEcSuVOm-1w1M2I1" },
    "24": { name: "Genshin Impact", link: "https://t.me/+BZhmU7N2ohwxOTk1" },
    "25": { name: "Latex cosplay", link: "https://t.me/+7Mb7FA8hB11hN2M1" },
    "26": { name: "Furry Hentai", link: "https://t.me/+prQM6T_7W-k1MjA1" },
    "27": { name: "ecchi", link: "https://t.me/+lSwmbqmVz582NjE1" },
    "28": { name: "more:3", link: "https://t.me/+bkNUnqpPFqgyZWYx" },
    "29": { name: "e-nada", link: "https://t.me/+49LIjQvIDKpmMjBh" },
    "30": { name: "Paizuri", link: "https://t.me/+gFBTrUMDcbU1OGE9" },
    "31": { name: "pokemon", link: "https://t.me/+-Fz1ZDv8ELE1NTQ1" },
    "32": { name: "kill la kill", link: "https://t.me/+fdGll5f1ovMwNWJl" },
    "33": { name: "hunter x hunter", link: "https://t.me/+W0vuvAPbGJhmODll" },
    "34": { name: "Lewd Neko", link: "https://t.me/+LZPD3cpJh9wzMTNl" },
    "35": { name: "Bunny Girls", link: "https://t.me/+7qHu2SOKeodhMjM1" },
    "36": { name: "thick", link: "https://t.me/+W71kiYLSTvM2NDQ1" },
    "37": { name: "Bondage", link: "https://t.me/+llOR1o-_iRk3Mzc1" },
    "38": { name: "Jam", link: "https://t.me/+l0g6CtbOxNM2YzUy" },
    "39": { name: "Ooko Opai", link: "https://t.me/+BNsNJBn1bTw4ZDAx" },
    "40": { name: "MoChinas", link: "https://t.me/+gKC2q_m_GNo1ZmNh" },
    "41": { name: "wota TBO", link: "https://t.me/+Y8SWxi43L10zM2Ey" },
    "42": { name: "Fap Zone", link: "https://t.me/+D4ecHyacQZY2MmE1" },
    "43": { name: "Booty", link: "https://t.me/+px5gTDpOyLgyMWQ0" },
    "44": { name: "DP152's", link: "https://t.me/+1rTP1fJhMANmM2Ex" },
    "45": { name: "horny house", link: "https://t.me/+a3XAb5ez6SVlNmIy" },
    "46": { name: "CumZone", link: "https://t.me/+ppXmSjwb4GRhZTgx" },
    "47": { name: "Hentai Randome", link: "https://t.me/+Ugm8mcVyvr1iZmIx" },
    "48": { name: "Dujin Dump", link: "https://t.me/+THRWQwTbfF1iNTM1" },
    "49": { name: "Kokoro Network", link: "https://t.me/KokoroNetwork" },
    "50": { name: "Asian Beauty", link: "https://t.me/+7rw8W3QZvlc3MmMy" },
    "51": { name: "Utopian Leaks", link: "https://telegram.me/utopianleaks" },
    "52": { name: "Pr00n", link: "https://telegram.me/pornodrive" },
    "53": { name: "Featured Creators 🔞", link: "https://telegram.me/joinchat/AW5EqAiG8UFlOGFh" },
    "54": { name: "Public Nu,dity", link: "https://telegram.me/random_porn" },
    "55": { name: "pfff_boom", link: "https://telegram.me/pfff_boom" },
    "56": { name: "Luciddreams", link: "https://t.me/luciddreams?start=_tgr_Yf_iCF1mOWU1" },
    "57": { name: "leecherxxx", link: "https://telegram.me/leecherxxx" },
    "58": { name: "Home Clips", link: "https://telegram.me/eronude" },
    "59": { name: "Bad Girls Videos", link: "https://t.me/+PpozazutRQg3YmU1" },
    "60": { name: "XXX Cloud", link: "https://telegram.me/joinchat/5EXKTI8kXA9iZjYy" },
    "61": { name: "Classic 18+", link: "https://telegram.me/classic_adult_films" },
    "62": { name: "Braz,zers", link: "https://telegram.me/joinchat/AAAAAFjVzKcL6FstTIhCnA" },
    "63": { name: "Cum on Face", link: "https://telegram.me/cumoffface" },
    "64": { name: "Dirt,y Memes", link: "https://telegram.me/DirtyMemesHub" },
    "65": { name: "telepo,rnogram", link: "https://telegram.me/telepornogram" },
    "66": { name: "Na,ked_tiktok2", link: "https://telegram.me/Naked_tiktok2" },
    "67": { name: "Exo,tic Videos", link: "https://telegram.me/joinchat/RmEKYbsZaexiYjIy" },
    "68": { name: "CINEMA", link: "https://telegram.me/joinchat/LE5THapOc0k4MTAy" },
    "69": { name: "Telegram Porn,stars", link: "https://telegram.me/BinanceBoxDaily" },
    "70": { name: "tattoos", link: "https://telegram.me/tattoos" },
    "71": { name: "Ga,y World", link: "https://telegram.me/gaypornworld" },
    "72": { name: "Tender Feet", link: "https://telegram.me/nyfeet" },
    "73": { name: "Real S,ex", link: "https://telegram.me/sexwife" },
    "74": { name: "explicit_scenes", link: "https://telegram.me/explicit_scenes" },
    "75": { name: "Explicit photos", link: "https://telegram.me/joinchat/AAAAAEQRBwcHqlrq977gkg" },
    "76": { name: "Double Penetration", link: "https://telegram.me/joinchat/COmq5d2L148zNjY0" },
    "77": { name: "Beautiful Girls", link: "https://telegram.me/b_babes" },
    "78": { name: "Naughty_America_premiumz", link: "https://telegram.me/Naughty_America_premiumz" },
    "79": { name: "Love BIte", link: "https://telegram.me/joinchat/AAAAAEphQ8XA8mzLTZxfBQ" },
    "80": { name: "Real Amature", link: "https://telegram.me/RealAmateursNG" },
    "81": { name: "Celebrity", link: "https://telegram.me/feets_soles" },
    "82": { name: "Full Length Vodeo", link: "https://telegram.me/joinchat/PjSZki6ofj04N2M5" },
    "83": { name: "Erot,icon", link: "https://telegram.me/clitorus" },
    "84": { name: "AI Girls", link: "https://telegram.me/ai_girls_beauty" },
    "85": { name: "Club 18", link: "https://telegram.me/BBCFWC" },
    "86": { name: "Hot Milf", link: "https://telegram.me/assmilfhots" },
    "87": { name: "Savage Black", link: "https://telegram.me/joinchat/AAAAAEKM_lvu5Yj9jdoUqw" },
    "88": { name: "Se..Xy Bu.tt", link: "https://telegram.me/buttsexy" },
    "89": { name: "Public Se,x", link: "https://telegram.me/joinchat/zxbDc-qaEZEwYWE6" },
    "90": { name: "Indian Girls", link: "https://telegram.me/desihotpobn" },
    "91": { name: "English Comics", link: "https://telegram.me/hellaway" },
    "92": { name: "Bad Girls", link: "https://t.me/+PpozazutRQg3YmU1" },
    "93": { name: "Ero,tic 18+", link: "https://telegram.me/myerotic" },
    "94": { name: "Les,bian", link: "https://telegram.me/joinchat/dZC_mNET07U4YzMy" },
    "95": { name: "sex,o_pedia", link: "https://telegram.me/sexo_pedia" },
    "96": { name: "laugaixinh", link: "https://telegram.me/laugaixinh" },
    "97": { name: "JapanesePorno", link: "https://telegram.me/JapanesePorno" },
    "98": { name: "BestAsianGirls", link: "https://telegram.me/BestAsianGirls" },
    "99": { name: "Cheati,ngWifes", link: "https://telegram.me/CheatingWifes" },
    "100": { name: "Porn 18+,", link: "https://telegram.me/joinchat/AAAAAEbyHdEum3w26SBQVQ" },
    "101": { name: "Asian Deshi", link: "https://telegram.me/sexyasian" },
    "102": { name: "Indian Bhabi", link: "https://telegram.me/joinchat/AAAAAE6Gs9ebxKJdvpUivg" },
    "103": { name: "indianadultcomics", link: "https://telegram.me/indianadultcomics" },
    "104": { name: "18+ Asian S,ex", link: "https://telegram.me/AsianSex" },
    "105": { name: "Dating chat 18++", link: "https://t.me/joinchat/qHYoXqFwPN4zOWFi" },
    "106": { name: "Mom son", link: "https://t.me/joinchat/7A8T9ooh8YU1ODQ1" },
    "107": { name: "देशी 🔞", link: "https://t.me/joinchat/JRoao0ARxgMzZTdl" },
    "108": { name: "English movie", link: "https://t.me/joinchat/Z_jFDbw-LklhY2Q1" },
    "109": { name: "4k pron video teraboxx", link: "https://t.me/joinchat/iJJnwnHZED0wMjNl" },
    "110": { name: "𝘼𝙡𝙡 𝙩𝙮𝙥𝙚𝙨 𝙫𝙞𝙙𝙚𝙤", link: "https://t.me/joinchat/IgOc0k48pusxNmFl" },
    "111": { name: "𝗗𝗮𝘁𝗶𝗻𝗴", link: "https://t.me/Chatting_Swapping_Dating" },
    "112": { name: "Instagram Group Girls", link: "https://t.me/joinchat/hepW0dFOSzcwZTll" },
    "113": { name: "𝗠𝗔𝗦𝗔𝗟𝗔🌶𝗖𝗛𝗔𝗧𝗭💋", link: "https://t.me/Masala_ChatzZ" },
    "114": { name: "World chatting", link: "https://t.me/joinchat/A9x59Pb2vIFhY2U1" },
    "115": { name: "Desi aunty lovers", link: "https://t.me/desiauntylover09" },
    "116": { name: "Pron 4k Movie 4K", link: "https://t.me/joinchat/9nuljHCBpVE4NmJl" },
    "117": { name: "ᴄʜᴀᴛᴛɪɴɢ ɢʀᴏᴜᴘ", link: "https://t.me/worldchatiinggroup" },
    "118": { name: "𝗪𝗢𝗥𝗟𝗗 𝗖𝗛𝗔𝗧𝗧𝗜𝗡𝗚 𝗚𝗥𝗢𝗨𝗣 👩‍❤️‍👨", link: "https://t.me/joinchat/b98sqTX5k1NjNjFh" },
    "119": { name: "CUTE GIRLS CHATTING", link: "https://t.me/cute_girls_chatting_group" },
    "120": { name: "👙Desi Porn Collections", link: "https://t.me/Desi_Porn_Collections" },
    "121": { name: "Tamil Housewife", link: "https://t.me/joinchat/8Q-pNFZsezM1ZjBl" },
    "122": { name: "Ｔａｍｉｌ Ｃｏｕｐｌｅｓ 💞", link: "https://t.me/tamilcouplesswap_chat" },
    "123": { name: "Girl's chatting", link: "https://t.me/joinchat/8fw0ZsB5LzYwNGU1" },
    "124": { name: "ᑭOᗰ🍒ᑭOᗰ 💬", link: "https://t.me/joinchat/KPWGoLOxyx9kNTll" },
    "125": { name: "Beautiful world 😍", link: "https://t.me/joinchat/gXJDUi-2P65kYzEx" },
    "126": { name: "Romantic friend", link: "https://t.me/joinchat/CuTJsS1HpvJhMGNl" },
    "127": { name: "Тошкен 71", link: "https://t.me/Towkent_chat_No1" },
    "128": { name: "Delhi Noida", link: "https://t.me/joinchat/0q_OWxWYK5xmOGFl" },
    "129": { name: "Kolkata Sexy Girl", link: "https://t.me/joinchat/B0ithb2HbyMxNDBl" },
    "130": { name: "Haryana Punjab Group", link: "https://t.me/GayWorldGIG" },
    "131": { name: "𝐒𝐎𝐑𝐆𝐀𝐋𝐎𝐆𝐀𝐌⚘ ⸙", link: "https://t.me/tamil_tamilhotchat" },
    "132": { name: "Hot ❤️ Hot ❤️", link: "https://t.me/joinchat/wT5J0D35fykzNWJl" },
    "133": { name: "Tamil verified couples💎", link: "https://t.me/Tamilcouples_verifiedcouples" },
    "134": { name: "MOM SON GROUP", link: "https://t.me/joinchat/HAG0DR2KDhdmOGVl" },
    "135": { name: "𝐂𝐎𝐔𝐏𝐋𝐄 𝐒𝐖𝐀𝐏 🐝", link: "https://t.me/joinchat/jvLYN9KPezJmMTQ1" },
    "136": { name: "Naughty Girls", link: "https://t.me/joinchat/RMychC3-V1w4YWM1" },
    "137": { name: "Viral Video Terabox", link: "https://t.me/joinchat/-sl_FkW-0GpkNWM1" },
    "138": { name: "Bangalore Dating", link: "https://t.me/bangalore_realmeet" },
    "139": { name: "Chat and mate", link: "https://t.me/joinchat/RqLk6e1ip_djN2Nl" },
    "140": { name: "Wife swapping", link: "https://t.me/joinchat/4Xahi2-Ri8U3MWU1" },
    "141": { name: "Confession X", link: "https://t.me/joinchat/OB0DCbOT7nU5ODg1" },
    "142": { name: "Kerala dating/hookup", link: "https://t.me/joinchat/ntWCj3StvRkwNDVl" },
    "143": { name: "𝕄𝕒𝕝𝕝𝕦 𝔾𝕒𝕪 ℍ𝕦𝕓", link: "https://t.me/mallugay_club" },
    "144": { name: "Desi Village girls", link: "https://t.me/joinchat/0siPFAlpU6EyY2Nl" },
    "145": { name: "Tamil Voice Chat 💋", link: "https://t.me/joinchat/5jVVyY3gpDJhMzll" },
    "146": { name: "𝗙𝗥𝗜𝗘𝗡𝗗𝗦 𝗖𝗛𝗔𝗧𝗧𝗜𝗡𝗚 𝗭𝗢𝗡𝗘 🦋🌷", link: "https://t.me/Freinds_group_hindi_grp" },
    "147": { name: "மங்கையர் விடுதி", link: "https://t.me/joinchat/ERIOefFy6HhiOWFl" },
    "148": { name: "International dating", link: "https://t.me/joinchat/WX12xstwSqE2YmE1" },
    "149": { name: "𝖪𝖾𝗋𝖺𝗅𝖺 𝖢𝖮𝖴𝖯𝖫𝖤𝖲 SWAP 𝖹𝗈𝗇𝖾 💋", link: "https://t.me/keralacoupleswap_chat" },
    "150": { name: "Kannada chatting group", link: "https://t.me/kannada_chatting_group4" },
    "151": { name: "🝮︎︎︎︎︎︎︎ 𝐍𝐀𝐔𝐆𝐇𝐓𝐘 𝐂𝐇𝐀𝐓𝐓𝐈𝐍𝐆 ✿︎", link: "https://t.me/joinchat/u1CuEzo5tWczZDk1" },
    "152": { name: "HOT GIRLS 🫣", link: "https://t.me/girls_group_world" },
    "153": { name: "Tollywood Beautys 💃 🔥💦", link: "https://t.me/joinchat/F-piXg1iRy8xNGJl" },
    "154": { name: "𝙍𝙄𝙎𝙆 𝙍𝙀𝙋𝙊𝙎𝙏", link: "https://t.me/joinchat/lpLd1Yd5PxBlNWM1" },
    "155": { name: "Video 🔞", link: "https://t.me/sexyvideo344" },
    "156": { name: "Sleeping pills 💊💦", link: "https://t.me/joinchat/4Imz9ih-AfA4MjM1" },
    "157": { name: "Cuckold World 2.0", link: "https://t.me/joinchat/ZQ5rrjj1jk4wYWEx" },
    "158": { name: "𝐂𝐚𝐦 𝐒𝐡𝐨𝐰 𝐙𝐨𝐧𝐞", link: "https://t.me/camshowzone" },
    "159": { name: "Tamil Couples freedom Hub 💞", link: "https://t.me/tamilfantasy_couples" },
    "160": { name: "Sleeping pills backup 💊💦", link: "https://t.me/joinchat/Kjf3yvF2Chw0MGQ1" },
    "161": { name: "🇭𝗼𝗧 🇳𝗶𝗴𝗵𝘁 🇨𝗹𝘂𝗯 🇲𝗮𝘀𝘁𝗶", link: "https://t.me/joinchat/GjkqWxN9Vwo0N2U0" },
    "162": { name: "Cum tribute 🍑", link: "https://t.me/joinchat/wXMwIXQYltMyODVl" },
    "163": { name: "Pʀᴏɴ hub 🔞", link: "https://t.me/joinchat/r75CtoOBRdcyOTY9" },
    "164": { name: "𝙍𝙀𝘿 𝙕𝙊𝙉𝙀", link: "https://t.me/joinchat/-8-utPPQx5I5ZjI1" },
    "165": { name: "Shikari backup", link: "https://t.me/joinchat/C35FFFyBEjthMDg1" },
    "166": { name: "Paid video call Indian", link: "https://t.me/cam_call_video_paid" },
    "167": { name: "Punjabi nazare 🥵", link: "https://t.me/joinchat/VboYmi3-BzE3NTE1" },
    "168": { name: "Bangalore Friends", link: "https://t.me/bangaloreFriends_club" },
    "169": { name: "COUPLE TO COUPLE", link: "https://t.me/joinchat/6qRoiAzxqNAwYTNl" },
    "170": { name: "Friendship X", link: "https://t.me/joinchat/WoqdIr6A_ZQzYzll" },
    "171": { name: "Kuwait ChatMatesUnite 🇰🇼", link: "https://t.me/ChatMatesUnite" },
    "172": { name: "Reena Babhi 💋💋", link: "https://t.me/joinchat/H4SqJZ8l3r9iNzc9" },
    "173": { name: "Desi hot 🥵 video", link: "https://t.me/joinchat/xHC38ij5eyEyNjE9" },
    "174": { name: "அடிச்சா 🫂கத்தாத டி💋", link: "https://t.me/joinchat/4vaesrG6WMs0ZWE9" },
    "175": { name: "hidden carmra", link: "https://t.me/joinchat/s9dZ80E0blZiNDk1" },
    "176": { name: "Desi girls", link: "https://t.me/desisexygirl67" },
    "177": { name: "Couple chatting", link: "https://t.me/wife_soping" },
    "178": { name: "Gujarati Wife", link: "https://t.me/Gujarat_wife_swapping" },
    "179": { name: "Mom son backup demo", link: "https://t.me/joinchat/6j6DXgMEZcNjZDk1" },
    "180": { name: "◄❥͜͡⃟⃝💖🩹꯭᪳𝄄─̌இரகசிய தோழி─", link: "https://t.me/joinchat/lyuvfyW6fLUwNTll" },
    "181": { name: "Desi hot 🧒 girl", link: "https://t.me/doxx699" },
    "182": { name: "Risk Repost🔥", link: "https://t.me/riskrepostreshare" },
    "183": { name: "🍒🇹‌𝐞𝐥𝐮𝐠𝐮 🇭‌𝐨𝐭 🇬‌𝐢𝐫𝐥𝐬 🇦‌𝐧𝐝 🇧‌𝐨𝐲𝐬🍒", link: "https://t.me/joinchat/sBR61EBy8wY3OGY1" },
    "184": { name: "Hot web series", link: "https://t.me/joinchat/TOk9WU6G3m41NmZl" },
    "185": { name: "🇽𝑌 ᯾ 𝐅𝐑𝐈𝐄𝐍𝐃𝐒𝐇𝐈𝐏 𝐙𝐎𝐍𝐄", link: "https://t.me/joinchat/bBS6OBwl-DphYjdk" },
    "186": { name: "Just Chatz 18+❤️", link: "https://t.me/chatinghuball" },
    "187": { name: "🇹𝅛𝆭𝐌𝐄𝐏𝐀𝐒𝐒 🇩𝐄𝐏𝐀𝐑𝐓𝐌𝐄𝐍𝐓』", link: "https://t.me/TIMEPASS_DEPARTMENT" },
    "188": { name: "Desi Fun", link: "https://t.me/desifundesi" },
    "189": { name: "𝙄𝙉𝘿𝙄𝘼𝙉 WIFE 𝙎𝙒𝘼𝙋𝙋𝙄𝙉𝙂", link: "https://t.me/real_swapping_wife_couple" },
    "190": { name: "Sleeping pills 3.0", link: "https://t.me/joinchat/BrwmNN-fd09hNDZl" },
    "191": { name: "ˡ᭄𝒈𝒊𝒓𝒍s Chatting ǤroนƤ☬꧂", link: "https://t.me/joinchat/csiJ8VNvrOA0ZTZl" },
    "192": { name: "𝗖𝗢𝗙𝗙𝗘𝗘 𝗖𝗛𝗔𝗧 ☕【﻿𝗖𝗖】", link: "https://t.me/randomcoffeequest" },
    "193": { name: "ⓖⓞⓞⓓ ⓒⓐⓜ", link: "https://t.me/joinchat/xhqukdM-iQhhMmE9" },
    "194": { name: "🕶️ 𝓥𝓪𝓪𝓷𝓰𝓴𝓪 𝓟𝓪𝔃𝓱𝓪𝓰𝓪𝓵𝓪𝓪𝓶 💥", link: "https://t.me/joinchat/WSpRVOylqR44NzY1" },
    "195": { name: "BLR PARTIES & NIGHTLIFE", link: "https://t.me/Bangalore_Parties_And_Fun" },
    "196": { name: "Telegram 4k Pron link", link: "https://t.me/joinchat/HAMPrHs8hKIyYTE1" },
    "197": { name: "꧁Teℓนgน꧂🔥HOT🔥", link: "https://t.me/joinchat/a4lY5gjoUdc2OGZl" },
    "198": { name: "Missed video club ( Chat )", link: "https://t.me/m_v_club_chat" },
    "199": { name: "Delhi cuck", link: "https://t.me/delhincrcucck" },
    "200": { name: "ACTRESS HUB - chat group", link: "https://t.me/actressHUBing" },
    "201": { name: "WIFE SWAPPING ✨", link: "https://t.me/bullsforcuxks" },
    "202": { name: "Sec sex", link: "https://t.me/joinchat/Cm1PP8vLc-k3Mjk9" },
    "203": { name: "Punjab Haryana wife swapping", link: "https://t.me/punjabharyanawifeswaping",
      "204": { name: "Bangladeshi 18+", link: "https://t.me/Bangladeshi_18_x" },
    "205": { name: "Only Bangla Adult Videos", link: "https://t.me/onlybanglaadultvideos" },
    "206": { name: "Bangladeshi Adult Xxx", link: "https://t.me/engkishkha" },
    "207": { name: "BENGALI MOM LOVER 💋", link: "https://t.me/+9-1fM6mg-8oxYjFl" },
    "208": { name: "কল বয় সার্ভিস 2.0", link: "https://t.me/arav378" },
    "209": { name: "ꜱᴇx ɢʀᴏᴜᴘ ʙᴅ", link: "https://t.me/+ihF_uvvY7i05ZDU1" },
    "210": { name: "naya Bangladeshi xxx videos 👙", link: "https://t.me/naya_bangladeshi" },
    "211": { name: "BangladeshiMouni roy xxx videos", link: "https://t.me/mx_player_website_netpal_bot" },
    "212": { name: "Bangladeshi girl rape videos", link: "Bangladeshi girl rape videos" },
    "213": { name: "Bangladeshi sexvideo🥵", link: "https://t.me/xxxvideo_pronvideo_adultvideo_x" },
    "214": { name: "XXX VIDEOS BANGLADESH 💦🥒🩱", link: "https://t.me/wwwxxxxncom" },
    },
    // Add more here manually
  };
  return Object.values(data);
};

export const SAMPLE_CHANNELS: Record<string, () => TelegramChannel[]> = {
  "1000": getChannels1000,
  "1500": getChannels1500,
  "2500": getChannels2500,
  "5000": getChannels5000,
};
