import { Package, TelegramChannel } from "../types";

export const PACKAGES: Package[] = [
  // 24 Hours
  { id: "1-D1", name: "Package 1-D1 (1000 Channels)", channels: 1000, priceBDT: 400, durationDays: 1 },
  { id: "2-D1", name: "Package 2-D1 (1500 Channels)", channels: 1500, priceBDT: 700, durationDays: 1 },
  { id: "3-D1", name: "Package 3-D1 (2500 Channels)", channels: 2500, priceBDT: 900, durationDays: 1 },
  { id: "4-D1", name: "Package 4-D1 (5000 Channels)", channels: 5000, priceBDT: 1900, durationDays: 1 },
  // 1 Week
  { id: "1-W1", name: "Package 1-W1 (1000 Channels)", channels: 1000, priceBDT: 1000, durationDays: 7 },
  { id: "2-W1", name: "Package 2-W1 (1500 Channels)", channels: 1500, priceBDT: 1500, durationDays: 7 },
  { id: "3-W1", name: "Package 3-W1 (2500 Channels)", channels: 2500, priceBDT: 2500, durationDays: 7 },
  { id: "4-W1", name: "Package 4-W1 (5000 Channels)", channels: 5000, priceBDT: 4000, durationDays: 7 },
  // Lifetime
  { id: "Lifetime", name: "Package Lifetime (5000 Channels)", channels: 5000, priceBDT: 122000, priceUSD: 1000, durationDays: 36500 },
];

export const getChannels1000 = () => {
  const data = {
    "1": { name: "MYLF", link: "https://t.me/mylfed" },
    "2": { name: "Koi no Yokan", link: "https://t.me/Koianime" },
    "3": { name: "ANIME WORLD 1", link: "https://t.me/ANIME_W1" },
    "4": { name: "@vickyy_san", link: "https://t.me/hdwallpaper4k4u" },
    "5": { name: "✅ Заявки принимаются", link: "https://t.me/animewallpaperfons" },
    "6": { name: "manga", link: "https://t.me/animemangaxtutti" },
    "7": { name: "Universe", link: "https://t.me/AnimeWallpaperUniverse" },
    "8": { name: "Son dibujos", link: "https://t.me/dibujosdedospersonasaburridas" },
    "9": { name: "Russua Aonha", link: "https://t.me/+cz6WONf9vM44NTgy" },
    "10": { name: "NSFW Warning", link: "https://t.me/+Zm4DUbJarvVmMGJk" },
    "11": { name: "Onku", link: "https://t.me/+L_yNHFEMBqVmZGYx" },
    "12": { name: "Hentai Universe", link: "https://t.me/+ueyQhA5sPplkZGE0" },
    "13": { name: "3D Jav", link: "https://t.me/+gBudv_7KJ_5kYjJl" },
    "14": { name: "Hentai Hunters", link: "https://t.me/+INFQKge4AJU1YmU9" },
    "15": { name: "Naruto", link: "https://t.me/+Au8dsm6UW9tjMzI1" },
    "16": { name: "Lewd Cosplay", link: "https://t.me/+S2-_xgIVljA0MzE1" },
    "17": { name: "Pantsu", link: "https://t.me/+6BFQ5JT_poIzMjVl" },
    "18": { name: "SWF", link: "https://t.me/GaleriaDelCosplay" },
    "19": { name: "Pokeputas", link: "https://t.me/+JibMn7AYUT04Njk5" },
    "20": { name: "Rule 34", link: "https://t.me/+sk_EOo9YkmIxNDMy" },
    "21": { name: "Hentai Anal", link: "https://t.me/+QLBK8Vz7kjNmOWZl" },
    "22": { name: "Quintessential", link: "https://t.me/+itYTq5Rjky1mYTg1" },
    "23": { name: "Fairy tale", link: "https://t.me/+iEcSuVOm-1w1M2I1" },
    "24": { name: "Genshin Impact", link: "https://t.me/+BZhmU7N2ohwxOTk1" },
    "25": { name: "Latex cosplay", link: "https://t.me/+7Mb7FA8hB11hN2M1" },
    "26": { name: "Furry Hentai", link: "https://t.me/+prQM6T_7W-k1MjA1" },
    "27": { name: "ecchi", link: "https://t.me/+lSwmbqmVz582NjE1" },
    "28": { name: "more:3", link: "https://t.me/+bkNUnqpPFqgyZWYx" },
    "29": { name: "e-nada", link: "https://t.me/+49LIjQvIDKpmMjBh" },
    "30": { name: "Paizuri", link: "https://t.me/+gFBTrUMDcbU1OGE9" },
    "31": { name: "pokemon", link: "https://t.me/+-Fz1ZDv8ELE1NTQ1" },
    "32": { name: "kill la kill", link: "https://t.me/+fdGll5f1ovMwNWJl" },
    "33": { name: "hunter x hunter", link: "https://t.me/+W0vuvAPbGJhmODll" },
    "34": { name: "Lewd Neko", link: "https://t.me/+LZPD3cpJh9wzMTNl" },
    "35": { name: "Bunny Girls", link: "https://t.me/+7qHu2SOKeodhMjM1" },
    "36": { name: "thick", link: "https://t.me/+W71kiYLSTvM2NDQ1" },
    "37": { name: "Bondage", link: "https://t.me/+llOR1o-_iRk3Mzc1" },
    "38": { name: "Jam", link: "https://t.me/+l0g6CtbOxNM2YzUy" },
    "39": { name: "Ooko Opai", link: "https://t.me/+BNsNJBn1bTw4ZDAx" },
    "40": { name: "MoChinas", link: "https://t.me/+gKC2q_m_GNo1ZmNh" },
    "41": { name: "wota TBO", link: "https://t.me/+Y8SWxi43L10zM2Ey" },
    "42": { name: "Fap Zone", link: "https://t.me/+D4ecHyacQZY2MmE1" },
    "43": { name: "Booty", link: "https://t.me/+px5gTDpOyLgyMWQ0" },
    "44": { name: "DP152's", link: "https://t.me/+1rTP1fJhMANmM2Ex" },
    "45": { name: "horny house", link: "https://t.me/+a3XAb5ez6SVlNmIy" },
    "46": { name: "CumZone", link: "https://t.me/+ppXmSjwb4GRhZTgx" },
    "47": { name: "Hentai Randome", link: "https://t.me/+Ugm8mcVyvr1iZmIx" },
    "48": { name: "Dujin Dump", link: "https://t.me/+THRWQwTbfF1iNTM1" },
    "49": { name: "Kokoro Network", link: "https://t.me/KokoroNetwork" },
    "50": { name: "Asian Beauty", link: "https://t.me/+7rw8W3QZvlc3MmMy" },
    "51": { name: "Utopian Leaks", link: "https://telegram.me/utopianleaks" },
    "52": { name: "Pr00n", link: "https://telegram.me/pornodrive" },
    "53": { name: "Featured Creators 🔞", link: "https://telegram.me/joinchat/AW5EqAiG8UFlOGFh" },
    "54": { name: "Public Nu,dity", link: "https://telegram.me/random_porn" },
    "55": { name: "pfff_boom", link: "https://telegram.me/pfff_boom" },
    "56": { name: "Luciddreams", link: "https://t.me/luciddreams?start=_tgr_Yf_iCF1mOWU1" },
    "57": { name: "leecherxxx", link: "https://telegram.me/leecherxxx" },
    "58": { name: "Home Clips", link: "https://telegram.me/eronude" },
    "59": { name: "Bad Girls Videos", link: "https://t.me/+PpozazutRQg3YmU1" },
    "60": { name: "XXX Cloud", link: "https://telegram.me/joinchat/5EXKTI8kXA9iZjYy" },
    "61": { name: "Classic 18+", link: "https://telegram.me/classic_adult_films" },
    "62": { name: "Braz,zers", link: "https://telegram.me/joinchat/AAAAAFjVzKcL6FstTIhCnA" },
    "63": { name: "Cum on Face", link: "https://telegram.me/cumoffface" },
    "64": { name: "Dirt,y Memes", link: "https://telegram.me/DirtyMemesHub" },
    "65": { name: "telepo,rnogram", link: "https://telegram.me/telepornogram" },
    "66": { name: "Na,ked_tiktok2", link: "https://telegram.me/Naked_tiktok2" },
    "67": { name: "Exo,tic Videos", link: "https://telegram.me/joinchat/RmEKYbsZaexiYjIy" },
    "68": { name: "CINEMA", link: "https://telegram.me/joinchat/LE5THapOc0k4MTAy" },
    "69": { name: "Telegram Porn,stars", link: "https://telegram.me/BinanceBoxDaily" },
    "70": { name: "tattoos", link: "https://telegram.me/tattoos" },
    "71": { name: "Ga,y World", link: "https://telegram.me/gaypornworld" },
    "72": { name: "Tender Feet", link: "https://telegram.me/nyfeet" },
    "73": { name: "Real S,ex", link: "https://telegram.me/sexwife" },
    "74": { name: "explicit_scenes", link: "https://telegram.me/explicit_scenes" },
    "75": { name: "Explicit photos", link: "https://telegram.me/joinchat/AAAAAEQRBwcHqlrq977gkg" },
    "76": { name: "Double Penetration", link: "https://telegram.me/joinchat/COmq5d2L148zNjY0" },
    "77": { name: "Beautiful Girls", link: "https://telegram.me/b_babes" },
    "78": { name: "Naughty_America_premiumz", link: "https://telegram.me/Naughty_America_premiumz" },
    "79": { name: "Love BIte", link: "https://telegram.me/joinchat/AAAAAEphQ8XA8mzLTZxfBQ" },
    "80": { name: "Real Amature", link: "https://telegram.me/RealAmateursNG" },
    "81": { name: "Celebrity", link: "https://telegram.me/feets_soles" },
    "82": { name: "Full Length Vodeo", link: "https://telegram.me/joinchat/PjSZki6ofj04N2M5" },
    "83": { name: "Erot,icon", link: "https://telegram.me/clitorus" },
    "84": { name: "AI Girls", link: "https://telegram.me/ai_girls_beauty" },
    "85": { name: "Club 18", link: "https://telegram.me/BBCFWC" },
    "86": { name: "Hot Milf", link: "https://telegram.me/assmilfhots" },
    "87": { name: "Savage Black", link: "https://telegram.me/joinchat/AAAAAEKM_lvu5Yj9jdoUqw" },
    "88": { name: "Se..Xy Bu.tt", link: "https://telegram.me/buttsexy" },
    "89": { name: "Public Se,x", link: "https://telegram.me/joinchat/zxbDc-qaEZEwYWE6" },
    "90": { name: "Indian Girls", link: "https://telegram.me/desihotpobn" },
    "91": { name: "English Comics", link: "https://telegram.me/hellaway" },
    "92": { name: "Bad Girls", link: "https://t.me/+PpozazutRQg3YmU1" },
    "93": { name: "Ero,tic 18+", link: "https://telegram.me/myerotic" },
    "94": { name: "Les,bian", link: "https://telegram.me/joinchat/dZC_mNET07U4YzMy" },
    "95": { name: "sex,o_pedia", link: "https://telegram.me/sexo_pedia" },
    "96": { name: "laugaixinh", link: "https://telegram.me/laugaixinh" },
    "97": { name: "JapanesePorno", link: "https://telegram.me/JapanesePorno" },
    "98": { name: "BestAsianGirls", link: "https://telegram.me/BestAsianGirls" },
    "99": { name: "Cheati,ngWifes", link: "https://telegram.me/CheatingWifes" },
    "100": { name: "Porn 18+,", link: "https://telegram.me/joinchat/AAAAAEbyHdEum3w26SBQVQ" },
    "101": { name: "Asian Deshi", link: "https://telegram.me/sexyasian" },
    "102": { name: "Indian Bhabi", link: "https://telegram.me/joinchat/AAAAAE6Gs9ebxKJdvpUivg" },
    "103": { name: "indianadultcomics", link: "https://telegram.me/indianadultcomics" },
    "104": { name: "18+ Asian S,ex", link: "https://telegram.me/AsianSex" }
    // Add more here manually
  };
  return Object.values(data);
};

export const getChannels1500 = () => {
  const data = {
    "1": { name: "MYLF", link: "https://t.me/mylfed" },
    "2": { name: "Koi no Yokan", link: "https://t.me/Koianime" },
    "3": { name: "ANIME WORLD 1", link: "https://t.me/ANIME_W1" },
    "4": { name: "@vickyy_san", link: "https://t.me/hdwallpaper4k4u" },
    "5": { name: "✅ Заявки принимаются", link: "https://t.me/animewallpaperfons" },
    "6": { name: "manga", link: "https://t.me/animemangaxtutti" },
    "7": { name: "Universe", link: "https://t.me/AnimeWallpaperUniverse" },
    "8": { name: "Son dibujos", link: "https://t.me/dibujosdedospersonasaburridas" },
    "9": { name: "Russua Aonha", link: "https://t.me/+cz6WONf9vM44NTgy" },
    "10": { name: "NSFW Warning", link: "https://t.me/+Zm4DUbJarvVmMGJk" },
    "11": { name: "Onku", link: "https://t.me/+L_yNHFEMBqVmZGYx" },
    "12": { name: "Hentai Universe", link: "https://t.me/+ueyQhA5sPplkZGE0" },
    "13": { name: "3D Jav", link: "https://t.me/+gBudv_7KJ_5kYjJl" },
    "14": { name: "Hentai Hunters", link: "https://t.me/+INFQKge4AJU1YmU9" },
    "15": { name: "Naruto", link: "https://t.me/+Au8dsm6UW9tjMzI1" },
    "16": { name: "Lewd Cosplay", link: "https://t.me/+S2-_xgIVljA0MzE1" },
    "17": { name: "Pantsu", link: "https://t.me/+6BFQ5JT_poIzMjVl" },
    "18": { name: "SWF", link: "https://t.me/GaleriaDelCosplay" },
    "19": { name: "Pokeputas", link: "https://t.me/+JibMn7AYUT04Njk5" },
    "20": { name: "Rule 34", link: "https://t.me/+sk_EOo9YkmIxNDMy" },
    "21": { name: "Hentai Anal", link: "https://t.me/+QLBK8Vz7kjNmOWZl" },
    "22": { name: "Quintessential", link: "https://t.me/+itYTq5Rjky1mYTg1" },
    "23": { name: "Fairy tale", link: "https://t.me/+iEcSuVOm-1w1M2I1" },
    "24": { name: "Genshin Impact", link: "https://t.me/+BZhmU7N2ohwxOTk1" },
    "25": { name: "Latex cosplay", link: "https://t.me/+7Mb7FA8hB11hN2M1" },
    "26": { name: "Furry Hentai", link: "https://t.me/+prQM6T_7W-k1MjA1" },
    "27": { name: "ecchi", link: "https://t.me/+lSwmbqmVz582NjE1" },
    "28": { name: "more:3", link: "https://t.me/+bkNUnqpPFqgyZWYx" },
    "29": { name: "e-nada", link: "https://t.me/+49LIjQvIDKpmMjBh" },
    "30": { name: "Paizuri", link: "https://t.me/+gFBTrUMDcbU1OGE9" },
    "31": { name: "pokemon", link: "https://t.me/+-Fz1ZDv8ELE1NTQ1" },
    "32": { name: "kill la kill", link: "https://t.me/+fdGll5f1ovMwNWJl" },
    "33": { name: "hunter x hunter", link: "https://t.me/+W0vuvAPbGJhmODll" },
    "34": { name: "Lewd Neko", link: "https://t.me/+LZPD3cpJh9wzMTNl" },
    "35": { name: "Bunny Girls", link: "https://t.me/+7qHu2SOKeodhMjM1" },
    "36": { name: "thick", link: "https://t.me/+W71kiYLSTvM2NDQ1" },
    "37": { name: "Bondage", link: "https://t.me/+llOR1o-_iRk3Mzc1" },
    "38": { name: "Jam", link: "https://t.me/+l0g6CtbOxNM2YzUy" },
    "39": { name: "Ooko Opai", link: "https://t.me/+BNsNJBn1bTw4ZDAx" },
    "40": { name: "MoChinas", link: "https://t.me/+gKC2q_m_GNo1ZmNh" },
    "41": { name: "wota TBO", link: "https://t.me/+Y8SWxi43L10zM2Ey" },
    "42": { name: "Fap Zone", link: "https://t.me/+D4ecHyacQZY2MmE1" },
    "43": { name: "Booty", link: "https://t.me/+px5gTDpOyLgyMWQ0" },
    "44": { name: "DP152's", link: "https://t.me/+1rTP1fJhMANmM2Ex" },
    "45": { name: "horny house", link: "https://t.me/+a3XAb5ez6SVlNmIy" },
    "46": { name: "CumZone", link: "https://t.me/+ppXmSjwb4GRhZTgx" },
    "47": { name: "Hentai Randome", link: "https://t.me/+Ugm8mcVyvr1iZmIx" },
    "48": { name: "Dujin Dump", link: "https://t.me/+THRWQwTbfF1iNTM1" },
    "49": { name: "Kokoro Network", link: "https://t.me/KokoroNetwork" },
    "50": { name: "Asian Beauty", link: "https://t.me/+7rw8W3QZvlc3MmMy" },
    "51": { name: "Utopian Leaks", link: "https://telegram.me/utopianleaks" },
    "52": { name: "Pr00n", link: "https://telegram.me/pornodrive" },
    "53": { name: "Featured Creators 🔞", link: "https://telegram.me/joinchat/AW5EqAiG8UFlOGFh" },
    "54": { name: "Public Nu,dity", link: "https://telegram.me/random_porn" },
    "55": { name: "pfff_boom", link: "https://telegram.me/pfff_boom" },
    "56": { name: "Luciddreams", link: "https://t.me/luciddreams?start=_tgr_Yf_iCF1mOWU1" },
    "57": { name: "leecherxxx", link: "https://telegram.me/leecherxxx" },
    "58": { name: "Home Clips", link: "https://telegram.me/eronude" },
    "59": { name: "Bad Girls Videos", link: "https://t.me/+PpozazutRQg3YmU1" },
    "60": { name: "XXX Cloud", link: "https://telegram.me/joinchat/5EXKTI8kXA9iZjYy" },
    "61": { name: "Classic 18+", link: "https://telegram.me/classic_adult_films" },
    "62": { name: "Braz,zers", link: "https://telegram.me/joinchat/AAAAAFjVzKcL6FstTIhCnA" },
    "63": { name: "Cum on Face", link: "https://telegram.me/cumoffface" },
    "64": { name: "Dirt,y Memes", link: "https://telegram.me/DirtyMemesHub" },
    "65": { name: "telepo,rnogram", link: "https://telegram.me/telepornogram" },
    "66": { name: "Na,ked_tiktok2", link: "https://telegram.me/Naked_tiktok2" },
    "67": { name: "Exo,tic Videos", link: "https://telegram.me/joinchat/RmEKYbsZaexiYjIy" },
    "68": { name: "CINEMA", link: "https://telegram.me/joinchat/LE5THapOc0k4MTAy" },
    "69": { name: "Telegram Porn,stars", link: "https://telegram.me/BinanceBoxDaily" },
    "70": { name: "tattoos", link: "https://telegram.me/tattoos" },
    "71": { name: "Ga,y World", link: "https://telegram.me/gaypornworld" },
    "72": { name: "Tender Feet", link: "https://telegram.me/nyfeet" },
    "73": { name: "Real S,ex", link: "https://telegram.me/sexwife" },
    "74": { name: "explicit_scenes", link: "https://telegram.me/explicit_scenes" },
    "75": { name: "Explicit photos", link: "https://telegram.me/joinchat/AAAAAEQRBwcHqlrq977gkg" },
    "76": { name: "Double Penetration", link: "https://telegram.me/joinchat/COmq5d2L148zNjY0" },
    "77": { name: "Beautiful Girls", link: "https://telegram.me/b_babes" },
    "78": { name: "Naughty_America_premiumz", link: "https://telegram.me/Naughty_America_premiumz" },
    "79": { name: "Love BIte", link: "https://telegram.me/joinchat/AAAAAEphQ8XA8mzLTZxfBQ" },
    "80": { name: "Real Amature", link: "https://telegram.me/RealAmateursNG" },
    "81": { name: "Celebrity", link: "https://telegram.me/feets_soles" },
    "82": { name: "Full Length Vodeo", link: "https://telegram.me/joinchat/PjSZki6ofj04N2M5" },
    "83": { name: "Erot,icon", link: "https://telegram.me/clitorus" },
    "84": { name: "AI Girls", link: "https://telegram.me/ai_girls_beauty" },
    "85": { name: "Club 18", link: "https://telegram.me/BBCFWC" },
    "86": { name: "Hot Milf", link: "https://telegram.me/assmilfhots" },
    "87": { name: "Savage Black", link: "https://telegram.me/joinchat/AAAAAEKM_lvu5Yj9jdoUqw" },
    "88": { name: "Se..Xy Bu.tt", link: "https://telegram.me/buttsexy" },
    "89": { name: "Public Se,x", link: "https://telegram.me/joinchat/zxbDc-qaEZEwYWE6" },
    "90": { name: "Indian Girls", link: "https://telegram.me/desihotpobn" },
    "91": { name: "English Comics", link: "https://telegram.me/hellaway" },
    "92": { name: "Bad Girls", link: "https://t.me/+PpozazutRQg3YmU1" },
    "93": { name: "Ero,tic 18+", link: "https://telegram.me/myerotic" },
    "94": { name: "Les,bian", link: "https://telegram.me/joinchat/dZC_mNET07U4YzMy" },
    "95": { name: "sex,o_pedia", link: "https://telegram.me/sexo_pedia" },
    "96": { name: "laugaixinh", link: "https://telegram.me/laugaixinh" },
    "97": { name: "JapanesePorno", link: "https://telegram.me/JapanesePorno" },
    "98": { name: "BestAsianGirls", link: "https://telegram.me/BestAsianGirls" },
    "99": { name: "Cheati,ngWifes", link: "https://telegram.me/CheatingWifes" },
    "100": { name: "Porn 18+,", link: "https://telegram.me/joinchat/AAAAAEbyHdEum3w26SBQVQ" },
    "101": { name: "Asian Deshi", link: "https://telegram.me/sexyasian" },
    "102": { name: "Indian Bhabi", link: "https://telegram.me/joinchat/AAAAAE6Gs9ebxKJdvpUivg" },
    "103": { name: "indianadultcomics", link: "https://telegram.me/indianadultcomics" },
    "104": { name: "18+ Asian S,ex", link: "https://telegram.me/AsianSex" }
    // Add more here manually
  };
  return Object.values(data);
};

export const getChannels2500 = () => {
  const data = {
    "1": { name: "MYLF", link: "https://t.me/mylfed" },
    "2": { name: "Koi no Yokan", link: "https://t.me/Koianime" },
    "3": { name: "ANIME WORLD 1", link: "https://t.me/ANIME_W1" },
    "4": { name: "@vickyy_san", link: "https://t.me/hdwallpaper4k4u" },
    "5": { name: "✅ Заявки принимаются", link: "https://t.me/animewallpaperfons" },
    "6": { name: "manga", link: "https://t.me/animemangaxtutti" },
    "7": { name: "Universe", link: "https://t.me/AnimeWallpaperUniverse" },
    "8": { name: "Son dibujos", link: "https://t.me/dibujosdedospersonasaburridas" },
    "9": { name: "Russua Aonha", link: "https://t.me/+cz6WONf9vM44NTgy" },
    "10": { name: "NSFW Warning", link: "https://t.me/+Zm4DUbJarvVmMGJk" },
    "11": { name: "Onku", link: "https://t.me/+L_yNHFEMBqVmZGYx" },
    "12": { name: "Hentai Universe", link: "https://t.me/+ueyQhA5sPplkZGE0" },
    "13": { name: "3D Jav", link: "https://t.me/+gBudv_7KJ_5kYjJl" },
    "14": { name: "Hentai Hunters", link: "https://t.me/+INFQKge4AJU1YmU9" },
    "15": { name: "Naruto", link: "https://t.me/+Au8dsm6UW9tjMzI1" },
    "16": { name: "Lewd Cosplay", link: "https://t.me/+S2-_xgIVljA0MzE1" },
    "17": { name: "Pantsu", link: "https://t.me/+6BFQ5JT_poIzMjVl" },
    "18": { name: "SWF", link: "https://t.me/GaleriaDelCosplay" },
    "19": { name: "Pokeputas", link: "https://t.me/+JibMn7AYUT04Njk5" },
    "20": { name: "Rule 34", link: "https://t.me/+sk_EOo9YkmIxNDMy" },
    "21": { name: "Hentai Anal", link: "https://t.me/+QLBK8Vz7kjNmOWZl" },
    "22": { name: "Quintessential", link: "https://t.me/+itYTq5Rjky1mYTg1" },
    "23": { name: "Fairy tale", link: "https://t.me/+iEcSuVOm-1w1M2I1" },
    "24": { name: "Genshin Impact", link: "https://t.me/+BZhmU7N2ohwxOTk1" },
    "25": { name: "Latex cosplay", link: "https://t.me/+7Mb7FA8hB11hN2M1" },
    "26": { name: "Furry Hentai", link: "https://t.me/+prQM6T_7W-k1MjA1" },
    "27": { name: "ecchi", link: "https://t.me/+lSwmbqmVz582NjE1" },
    "28": { name: "more:3", link: "https://t.me/+bkNUnqpPFqgyZWYx" },
    "29": { name: "e-nada", link: "https://t.me/+49LIjQvIDKpmMjBh" },
    "30": { name: "Paizuri", link: "https://t.me/+gFBTrUMDcbU1OGE9" },
    "31": { name: "pokemon", link: "https://t.me/+-Fz1ZDv8ELE1NTQ1" },
    "32": { name: "kill la kill", link: "https://t.me/+fdGll5f1ovMwNWJl" },
    "33": { name: "hunter x hunter", link: "https://t.me/+W0vuvAPbGJhmODll" },
    "34": { name: "Lewd Neko", link: "https://t.me/+LZPD3cpJh9wzMTNl" },
    "35": { name: "Bunny Girls", link: "https://t.me/+7qHu2SOKeodhMjM1" },
    "36": { name: "thick", link: "https://t.me/+W71kiYLSTvM2NDQ1" },
    "37": { name: "Bondage", link: "https://t.me/+llOR1o-_iRk3Mzc1" },
    "38": { name: "Jam", link: "https://t.me/+l0g6CtbOxNM2YzUy" },
    "39": { name: "Ooko Opai", link: "https://t.me/+BNsNJBn1bTw4ZDAx" },
    "40": { name: "MoChinas", link: "https://t.me/+gKC2q_m_GNo1ZmNh" },
    "41": { name: "wota TBO", link: "https://t.me/+Y8SWxi43L10zM2Ey" },
    "42": { name: "Fap Zone", link: "https://t.me/+D4ecHyacQZY2MmE1" },
    "43": { name: "Booty", link: "https://t.me/+px5gTDpOyLgyMWQ0" },
    "44": { name: "DP152's", link: "https://t.me/+1rTP1fJhMANmM2Ex" },
    "45": { name: "horny house", link: "https://t.me/+a3XAb5ez6SVlNmIy" },
    "46": { name: "CumZone", link: "https://t.me/+ppXmSjwb4GRhZTgx" },
    "47": { name: "Hentai Randome", link: "https://t.me/+Ugm8mcVyvr1iZmIx" },
    "48": { name: "Dujin Dump", link: "https://t.me/+THRWQwTbfF1iNTM1" },
    "49": { name: "Kokoro Network", link: "https://t.me/KokoroNetwork" },
    "50": { name: "Asian Beauty", link: "https://t.me/+7rw8W3QZvlc3MmMy" },
    "51": { name: "Utopian Leaks", link: "https://telegram.me/utopianleaks" },
    "52": { name: "Pr00n", link: "https://telegram.me/pornodrive" },
    "53": { name: "Featured Creators 🔞", link: "https://telegram.me/joinchat/AW5EqAiG8UFlOGFh" },
    "54": { name: "Public Nu,dity", link: "https://telegram.me/random_porn" },
    "55": { name: "pfff_boom", link: "https://telegram.me/pfff_boom" },
    "56": { name: "Luciddreams", link: "https://t.me/luciddreams?start=_tgr_Yf_iCF1mOWU1" },
    "57": { name: "leecherxxx", link: "https://telegram.me/leecherxxx" },
    "58": { name: "Home Clips", link: "https://telegram.me/eronude" },
    "59": { name: "Bad Girls Videos", link: "https://t.me/+PpozazutRQg3YmU1" },
    "60": { name: "XXX Cloud", link: "https://telegram.me/joinchat/5EXKTI8kXA9iZjYy" },
    "61": { name: "Classic 18+", link: "https://telegram.me/classic_adult_films" },
    "62": { name: "Braz,zers", link: "https://telegram.me/joinchat/AAAAAFjVzKcL6FstTIhCnA" },
    "63": { name: "Cum on Face", link: "https://telegram.me/cumoffface" },
    "64": { name: "Dirt,y Memes", link: "https://telegram.me/DirtyMemesHub" },
    "65": { name: "telepo,rnogram", link: "https://telegram.me/telepornogram" },
    "66": { name: "Na,ked_tiktok2", link: "https://telegram.me/Naked_tiktok2" },
    "67": { name: "Exo,tic Videos", link: "https://telegram.me/joinchat/RmEKYbsZaexiYjIy" },
    "68": { name: "CINEMA", link: "https://telegram.me/joinchat/LE5THapOc0k4MTAy" },
    "69": { name: "Telegram Porn,stars", link: "https://telegram.me/BinanceBoxDaily" },
    "70": { name: "tattoos", link: "https://telegram.me/tattoos" },
    "71": { name: "Ga,y World", link: "https://telegram.me/gaypornworld" },
    "72": { name: "Tender Feet", link: "https://telegram.me/nyfeet" },
    "73": { name: "Real S,ex", link: "https://telegram.me/sexwife" },
    "74": { name: "explicit_scenes", link: "https://telegram.me/explicit_scenes" },
    "75": { name: "Explicit photos", link: "https://telegram.me/joinchat/AAAAAEQRBwcHqlrq977gkg" },
    "76": { name: "Double Penetration", link: "https://telegram.me/joinchat/COmq5d2L148zNjY0" },
    "77": { name: "Beautiful Girls", link: "https://telegram.me/b_babes" },
    "78": { name: "Naughty_America_premiumz", link: "https://telegram.me/Naughty_America_premiumz" },
    "79": { name: "Love BIte", link: "https://telegram.me/joinchat/AAAAAEphQ8XA8mzLTZxfBQ" },
    "80": { name: "Real Amature", link: "https://telegram.me/RealAmateursNG" },
    "81": { name: "Celebrity", link: "https://telegram.me/feets_soles" },
    "82": { name: "Full Length Vodeo", link: "https://telegram.me/joinchat/PjSZki6ofj04N2M5" },
    "83": { name: "Erot,icon", link: "https://telegram.me/clitorus" },
    "84": { name: "AI Girls", link: "https://telegram.me/ai_girls_beauty" },
    "85": { name: "Club 18", link: "https://telegram.me/BBCFWC" },
    "86": { name: "Hot Milf", link: "https://telegram.me/assmilfhots" },
    "87": { name: "Savage Black", link: "https://telegram.me/joinchat/AAAAAEKM_lvu5Yj9jdoUqw" },
    "88": { name: "Se..Xy Bu.tt", link: "https://telegram.me/buttsexy" },
    "89": { name: "Public Se,x", link: "https://telegram.me/joinchat/zxbDc-qaEZEwYWE6" },
    "90": { name: "Indian Girls", link: "https://telegram.me/desihotpobn" },
    "91": { name: "English Comics", link: "https://telegram.me/hellaway" },
    "92": { name: "Bad Girls", link: "https://t.me/+PpozazutRQg3YmU1" },
    "93": { name: "Ero,tic 18+", link: "https://telegram.me/myerotic" },
    "94": { name: "Les,bian", link: "https://telegram.me/joinchat/dZC_mNET07U4YzMy" },
    "95": { name: "sex,o_pedia", link: "https://telegram.me/sexo_pedia" },
    "96": { name: "laugaixinh", link: "https://telegram.me/laugaixinh" },
    "97": { name: "JapanesePorno", link: "https://telegram.me/JapanesePorno" },
    "98": { name: "BestAsianGirls", link: "https://telegram.me/BestAsianGirls" },
    "99": { name: "Cheati,ngWifes", link: "https://telegram.me/CheatingWifes" },
    "100": { name: "Porn 18+,", link: "https://telegram.me/joinchat/AAAAAEbyHdEum3w26SBQVQ" },
    "101": { name: "Asian Deshi", link: "https://telegram.me/sexyasian" },
    "102": { name: "Indian Bhabi", link: "https://telegram.me/joinchat/AAAAAE6Gs9ebxKJdvpUivg" },
    "103": { name: "indianadultcomics", link: "https://telegram.me/indianadultcomics" },
    "104": { name: "18+ Asian S,ex", link: "https://telegram.me/AsianSex" }
    // Add more here manually
  };
  return Object.values(data);
};

export const getChannels5000 = () => {
  const data = {
    "1": { name: "MYLF", link: "https://t.me/mylfed" },
    "2": { name: "Koi no Yokan", link: "https://t.me/Koianime" },
    "3": { name: "ANIME WORLD 1", link: "https://t.me/ANIME_W1" },
    "4": { name: "@vickyy_san", link: "https://t.me/hdwallpaper4k4u" },
    "5": { name: "✅ Заявки принимаются", link: "https://t.me/animewallpaperfons" },
    "6": { name: "manga", link: "https://t.me/animemangaxtutti" },
    "7": { name: "Universe", link: "https://t.me/AnimeWallpaperUniverse" },
    "8": { name: "Son dibujos", link: "https://t.me/dibujosdedospersonasaburridas" },
    "9": { name: "Russua Aonha", link: "https://t.me/+cz6WONf9vM44NTgy" },
    "10": { name: "NSFW Warning", link: "https://t.me/+Zm4DUbJarvVmMGJk" },
    "11": { name: "Onku", link: "https://t.me/+L_yNHFEMBqVmZGYx" },
    "12": { name: "Hentai Universe", link: "https://t.me/+ueyQhA5sPplkZGE0" },
    "13": { name: "3D Jav", link: "https://t.me/+gBudv_7KJ_5kYjJl" },
    "14": { name: "Hentai Hunters", link: "https://t.me/+INFQKge4AJU1YmU9" },
    "15": { name: "Naruto", link: "https://t.me/+Au8dsm6UW9tjMzI1" },
    "16": { name: "Lewd Cosplay", link: "https://t.me/+S2-_xgIVljA0MzE1" },
    "17": { name: "Pantsu", link: "https://t.me/+6BFQ5JT_poIzMjVl" },
    "18": { name: "SWF", link: "https://t.me/GaleriaDelCosplay" },
    "19": { name: "Pokeputas", link: "https://t.me/+JibMn7AYUT04Njk5" },
    "20": { name: "Rule 34", link: "https://t.me/+sk_EOo9YkmIxNDMy" },
    "21": { name: "Hentai Anal", link: "https://t.me/+QLBK8Vz7kjNmOWZl" },
    "22": { name: "Quintessential", link: "https://t.me/+itYTq5Rjky1mYTg1" },
    "23": { name: "Fairy tale", link: "https://t.me/+iEcSuVOm-1w1M2I1" },
    "24": { name: "Genshin Impact", link: "https://t.me/+BZhmU7N2ohwxOTk1" },
    "25": { name: "Latex cosplay", link: "https://t.me/+7Mb7FA8hB11hN2M1" },
    "26": { name: "Furry Hentai", link: "https://t.me/+prQM6T_7W-k1MjA1" },
    "27": { name: "ecchi", link: "https://t.me/+lSwmbqmVz582NjE1" },
    "28": { name: "more:3", link: "https://t.me/+bkNUnqpPFqgyZWYx" },
    "29": { name: "e-nada", link: "https://t.me/+49LIjQvIDKpmMjBh" },
    "30": { name: "Paizuri", link: "https://t.me/+gFBTrUMDcbU1OGE9" },
    "31": { name: "pokemon", link: "https://t.me/+-Fz1ZDv8ELE1NTQ1" },
    "32": { name: "kill la kill", link: "https://t.me/+fdGll5f1ovMwNWJl" },
    "33": { name: "hunter x hunter", link: "https://t.me/+W0vuvAPbGJhmODll" },
    "34": { name: "Lewd Neko", link: "https://t.me/+LZPD3cpJh9wzMTNl" },
    "35": { name: "Bunny Girls", link: "https://t.me/+7qHu2SOKeodhMjM1" },
    "36": { name: "thick", link: "https://t.me/+W71kiYLSTvM2NDQ1" },
    "37": { name: "Bondage", link: "https://t.me/+llOR1o-_iRk3Mzc1" },
    "38": { name: "Jam", link: "https://t.me/+l0g6CtbOxNM2YzUy" },
    "39": { name: "Ooko Opai", link: "https://t.me/+BNsNJBn1bTw4ZDAx" },
    "40": { name: "MoChinas", link: "https://t.me/+gKC2q_m_GNo1ZmNh" },
    "41": { name: "wota TBO", link: "https://t.me/+Y8SWxi43L10zM2Ey" },
    "42": { name: "Fap Zone", link: "https://t.me/+D4ecHyacQZY2MmE1" },
    "43": { name: "Booty", link: "https://t.me/+px5gTDpOyLgyMWQ0" },
    "44": { name: "DP152's", link: "https://t.me/+1rTP1fJhMANmM2Ex" },
    "45": { name: "horny house", link: "https://t.me/+a3XAb5ez6SVlNmIy" },
    "46": { name: "CumZone", link: "https://t.me/+ppXmSjwb4GRhZTgx" },
    "47": { name: "Hentai Randome", link: "https://t.me/+Ugm8mcVyvr1iZmIx" },
    "48": { name: "Dujin Dump", link: "https://t.me/+THRWQwTbfF1iNTM1" },
    "49": { name: "Kokoro Network", link: "https://t.me/KokoroNetwork" },
    "50": { name: "Asian Beauty", link: "https://t.me/+7rw8W3QZvlc3MmMy" },
    "51": { name: "Utopian Leaks", link: "https://telegram.me/utopianleaks" },
    "52": { name: "Pr00n", link: "https://telegram.me/pornodrive" },
    "53": { name: "Featured Creators 🔞", link: "https://telegram.me/joinchat/AW5EqAiG8UFlOGFh" },
    "54": { name: "Public Nu,dity", link: "https://telegram.me/random_porn" },
    "55": { name: "pfff_boom", link: "https://telegram.me/pfff_boom" },
    "56": { name: "Luciddreams", link: "https://t.me/luciddreams?start=_tgr_Yf_iCF1mOWU1" },
    "57": { name: "leecherxxx", link: "https://telegram.me/leecherxxx" },
    "58": { name: "Home Clips", link: "https://telegram.me/eronude" },
    "59": { name: "Bad Girls Videos", link: "https://t.me/+PpozazutRQg3YmU1" },
    "60": { name: "XXX Cloud", link: "https://telegram.me/joinchat/5EXKTI8kXA9iZjYy" },
    "61": { name: "Classic 18+", link: "https://telegram.me/classic_adult_films" },
    "62": { name: "Braz,zers", link: "https://telegram.me/joinchat/AAAAAFjVzKcL6FstTIhCnA" },
    "63": { name: "Cum on Face", link: "https://telegram.me/cumoffface" },
    "64": { name: "Dirt,y Memes", link: "https://telegram.me/DirtyMemesHub" },
    "65": { name: "telepo,rnogram", link: "https://telegram.me/telepornogram" },
    "66": { name: "Na,ked_tiktok2", link: "https://telegram.me/Naked_tiktok2" },
    "67": { name: "Exo,tic Videos", link: "https://telegram.me/joinchat/RmEKYbsZaexiYjIy" },
    "68": { name: "CINEMA", link: "https://telegram.me/joinchat/LE5THapOc0k4MTAy" },
    "69": { name: "Telegram Porn,stars", link: "https://telegram.me/BinanceBoxDaily" },
    "70": { name: "tattoos", link: "https://telegram.me/tattoos" },
    "71": { name: "Ga,y World", link: "https://telegram.me/gaypornworld" },
    "72": { name: "Tender Feet", link: "https://telegram.me/nyfeet" },
    "73": { name: "Real S,ex", link: "https://telegram.me/sexwife" },
    "74": { name: "explicit_scenes", link: "https://telegram.me/explicit_scenes" },
    "75": { name: "Explicit photos", link: "https://telegram.me/joinchat/AAAAAEQRBwcHqlrq977gkg" },
    "76": { name: "Double Penetration", link: "https://telegram.me/joinchat/COmq5d2L148zNjY0" },
    "77": { name: "Beautiful Girls", link: "https://telegram.me/b_babes" },
    "78": { name: "Naughty_America_premiumz", link: "https://telegram.me/Naughty_America_premiumz" },
    "79": { name: "Love BIte", link: "https://telegram.me/joinchat/AAAAAEphQ8XA8mzLTZxfBQ" },
    "80": { name: "Real Amature", link: "https://telegram.me/RealAmateursNG" },
    "81": { name: "Celebrity", link: "https://telegram.me/feets_soles" },
    "82": { name: "Full Length Vodeo", link: "https://telegram.me/joinchat/PjSZki6ofj04N2M5" },
    "83": { name: "Erot,icon", link: "https://telegram.me/clitorus" },
    "84": { name: "AI Girls", link: "https://telegram.me/ai_girls_beauty" },
    "85": { name: "Club 18", link: "https://telegram.me/BBCFWC" },
    "86": { name: "Hot Milf", link: "https://telegram.me/assmilfhots" },
    "87": { name: "Savage Black", link: "https://telegram.me/joinchat/AAAAAEKM_lvu5Yj9jdoUqw" },
    "88": { name: "Se..Xy Bu.tt", link: "https://telegram.me/buttsexy" },
    "89": { name: "Public Se,x", link: "https://telegram.me/joinchat/zxbDc-qaEZEwYWE6" },
    "90": { name: "Indian Girls", link: "https://telegram.me/desihotpobn" },
    "91": { name: "English Comics", link: "https://telegram.me/hellaway" },
    "92": { name: "Bad Girls", link: "https://t.me/+PpozazutRQg3YmU1" },
    "93": { name: "Ero,tic 18+", link: "https://telegram.me/myerotic" },
    "94": { name: "Les,bian", link: "https://telegram.me/joinchat/dZC_mNET07U4YzMy" },
    "95": { name: "sex,o_pedia", link: "https://telegram.me/sexo_pedia" },
    "96": { name: "laugaixinh", link: "https://telegram.me/laugaixinh" },
    "97": { name: "JapanesePorno", link: "https://telegram.me/JapanesePorno" },
    "98": { name: "BestAsianGirls", link: "https://telegram.me/BestAsianGirls" },
    "99": { name: "Cheati,ngWifes", link: "https://telegram.me/CheatingWifes" },
    "100": { name: "Porn 18+,", link: "https://telegram.me/joinchat/AAAAAEbyHdEum3w26SBQVQ" },
    "101": { name: "Asian Deshi", link: "https://telegram.me/sexyasian" },
    "102": { name: "Indian Bhabi", link: "https://telegram.me/joinchat/AAAAAE6Gs9ebxKJdvpUivg" },
    "103": { name: "indianadultcomics", link: "https://telegram.me/indianadultcomics" },
    "104": { name: "18+ Asian S,ex", link: "https://telegram.me/AsianSex" }
    // Add more here manually
  };
  return Object.values(data);
};

export const SAMPLE_CHANNELS: Record<string, () => TelegramChannel[]> = {
  "1000": getChannels1000,
  "1500": getChannels1500,
  "2500": getChannels2500,
  "5000": getChannels5000,
};
